/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef MOS6502_MOS6502_INCLUDE_MOS6502_CODE_H
#define MOS6502_MOS6502_INCLUDE_MOS6502_CODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define MOS6502_CODE_STATE
#define MOS6502_CODE_INIT(s)
#define MOS6502_CODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* MOS6502_MOS6502_INCLUDE_MOS6502_CODE_H */
