/* Generated by gep (125/05/23 10:52:00) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_MOS6502_INCLUDE_MOS6502_DECODE_H
#define GLISS_MOS6502_INCLUDE_MOS6502_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#define MOS6502_DECODE_STATE
#define MOS6502_DECODE_INIT(s)
#define MOS6502_DECODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_MOS6502_INCLUDE_MOS6502_DECODE_H */
