/* Generated by gep (125/04/14 21:47:43) copyright (c) 2008 IRIT - UPS */

#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <avr/api.h>
#include "platform.h"
#include <avr/env.h>
#include <avr/macros.h>
#include <avr/config.h>


static char *avr_string_ident[] = {
	"AVR_UNKNOWN",
	"AVR_CALL_D__LP_04X_RP_",
	"AVR_JMP_D__LP_04X_RP_",
	"AVR_STS_D__RD",
	"AVR_LDS_RD__0X04X",
	"AVR_BRID___P_D__3B__P_04X",
	"AVR_BRIE___P_D__3B__P_04X",
	"AVR_BRVC___P_D__3B__P_04X",
	"AVR_BRVS___P_D__3B__P_04X",
	"AVR_BRTC___P_D__3B__P_04X",
	"AVR_BRTS___P_D__3B__P_04X",
	"AVR_BRHC___P_D__3B__P_04X",
	"AVR_BRHS___P_D__3B__P_04X",
	"AVR_BRLT___P_D__3B__P_04X",
	"AVR_BRGE___P_D__3B__P_04X",
	"AVR_BRPL___P_D__3B__P_04X",
	"AVR_BRMI___P_D__3B__P_04X",
	"AVR_BRCC___P_D__3B__P_04X",
	"AVR_BRCS___P_D__3B__P_04X",
	"AVR_BRNE___P_D__3B__P_04X",
	"AVR_BREQ___P_D__3B__P_04X",
	"AVR_SBIC_IOD__D",
	"AVR_SBIC_IOD__D_0",
	"AVR_SBRS_RD__D",
	"AVR_SBRC_RD__D",
	"AVR_CPI_RD__0X02X__3B_D",
	"AVR_CPC_RD__RD",
	"AVR_CP_RD__RD",
	"AVR_CSPE_RD__RD",
	"AVR_RETI",
	"AVR_RET",
	"AVR_ICALL",
	"AVR_RCALL_D__LP_04X_RP_",
	"AVR_IJMP",
	"AVR_RJMP___P_D__3B_04X",
	"AVR_FMULSU_RD__RD",
	"AVR_FMULS_RD__RD",
	"AVR_FMUL_RD__RD",
	"AVR_MULSU_RD__RD",
	"AVR_MULS_RD__RD",
	"AVR_MUL_RD__RD",
	"AVR_DEC_RD",
	"AVR_INC_RD",
	"AVR_NEG_RD",
	"AVR_COM_RD",
	"AVR_EOR_RD__RD",
	"AVR_ORI_RD__D",
	"AVR_OR_RD__RD",
	"AVR_ANDI_RD__RD",
	"AVR_AND_RD__RD",
	"AVR_SBIW_RD_3ARD__D",
	"AVR_SBCI_RD__D",
	"AVR_SBC_RD__RD",
	"AVR_SUBI_RD__D",
	"AVR_SUB_RD__RD",
	"AVR_ADIW_RD_3ARD__D",
	"AVR_ADC_RD__RD",
	"AVR_ADD_RD__RD",
	"AVR_CBI_IOD__D",
	"AVR_SBI_IOD__D",
	"AVR_CLH",
	"AVR_SEH",
	"AVR_CLT",
	"AVR_SET",
	"AVR_CLV",
	"AVR_SEV",
	"AVR_CLS",
	"AVR_SES",
	"AVR_CLI",
	"AVR_SEI",
	"AVR_CLZ",
	"AVR_SEZ",
	"AVR_CLN",
	"AVR_SEN",
	"AVR_CLC",
	"AVR_SEC",
	"AVR_BST_RD__D",
	"AVR_BLD_RD__D",
	"AVR_SWAP_RD",
	"AVR_ASR_RD",
	"AVR_ROR_RD",
	"AVR_LSR_RD",
	"AVR_LPM_RD__Z_P_",
	"AVR_LPM_RD__Z",
	"AVR_LPM",
	"AVR_LAC_Z__RD",
	"AVR_LAT_Z__RD",
	"AVR_LAS_Z__RD",
	"AVR_XCH_Z__RD",
	"AVR_POP_RD",
	"AVR_PUSH_RD",
	"AVR_OUT_D__RD",
	"AVR_IN_RD__D",
	"AVR_ST_Z_P___RD",
	"AVR_ST__M_Z__RD",
	"AVR_STD_Z_P_D__RD",
	"AVR_ST_Y_P___RD",
	"AVR_ST__M_Y__RD",
	"AVR_STD_Y_P_D__RD",
	"AVR_ST_X_P___RD",
	"AVR_ST__M_X__RD",
	"AVR_ST_X__RD",
	"AVR_LDD_RD__Z_P_D",
	"AVR_LD_RD___M_Z",
	"AVR_LD_RD__Z_P_",
	"AVR_LDD_RD__Y_P_D",
	"AVR_LD_RD___M_Y",
	"AVR_LD_RD__Y_P_",
	"AVR_LD_RD___M_X",
	"AVR_LD_RD__X_P_",
	"AVR_LD_RD__X",
	"AVR_MOVW_RD_3AD__RD_3AD",
	"AVR_MOV_RD__RD",
	"AVR_LDI_RD__D"
};

/* execution code table */
typedef void (*avr_code_function_t)(avr_state_t *, avr_inst_t *);
extern avr_code_function_t avr_code_table[];


char *avr_get_string_ident(avr_ident_t id)
{
	return avr_string_ident[id];
}

static unsigned long avr_size_ident[] = {
	16,
	32,
	32,
	32,
	32,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16,
	16
};

unsigned long avr_get_inst_size_from_id(avr_ident_t id) {
	return avr_size_ident[id];
}

unsigned long avr_get_inst_size(avr_inst_t* inst) {
	return avr_size_ident[inst->ident];
}

/**
 * @typedef avr_platform_t
 * This opaque type allows to represent an hardware and software platform.
 * It includes information about:
 * @li the hardware memories,
 * @li the module data (including system calls and interruption support).
 */


/**
 * Build a new platform for the platform avr.
 * @return	Created platform or null if there is no more memory (see errno).
 * @note To release the platform, use avr_unlock_platform().
 */
avr_platform_t *avr_new_platform(void) {
	avr_platform_t *pf;
	char *assert;

	/* allocation */
	pf = (avr_platform_t *)calloc(1, sizeof(avr_platform_t));
	if(pf == NULL) {
		errno = ENOMEM;
		return NULL;
	}
	/* the new platform is not locked yet */
	pf->usage = 0;

	/* other init */
	pf->sys_env = calloc(1, sizeof(avr_env_t));
	if(pf->sys_env == NULL) {
		errno = ENOMEM;
		free(pf);
		return NULL;
	}

	/* memory initialization */
	pf->mems.named.FLASH = avr_mem_new();
	if(pf->mems.named.FLASH == NULL) {
		free(pf->sys_env);
		free(pf);
		return NULL;
	}
	pf->mems.named.M = avr_mem_new();
	if(pf->mems.named.M == NULL) {
		free(pf->sys_env);
		free(pf);
		return NULL;
	}


	/* module initialization */
	AVR_MEM_INIT(pf);
	AVR_GRT_INIT(pf);
	AVR_ERROR_INIT(pf);
	AVR_GEN_INT_INIT(pf);
	AVR_ENV_INIT(pf);
	AVR_LOADER_INIT(pf);
	AVR_CODE_INIT(pf);


	/* assertion check */
	assert = getenv("GLISS_NDEBUG");
	if(assert != NULL && strcasecmp(assert, "yes") == 0)
		avr_assert_enable = 0;

	/* return platform */
	return pf;
}


/**
 * Get a memory in the platform.
 * @param platform	Platform to get memory from.
 * @param index		Index of the memory to get.
 * @return			Requested memory.
 */
avr_memory_t *avr_get_memory(avr_platform_t *platform, int index) {
	if (platform == NULL)
		return NULL;

	return platform->mems.array[index];
}


/**
 * return the system info (argc, argv ...), meaningless
 * if used when no program loaded
 * @param	platform	Platform to get system info from.
 * @return		Requested system info.
 */
avr_env_t *avr_get_sys_env(avr_platform_t *platform)
{
	if (platform == NULL)
		return NULL;

	return platform->sys_env;
}


/**
 * Ensure that the platform is not released before a matching
 * avr_platform_unlock() is performed.
 * @param platform	Platform to lock.
 */
void avr_lock_platform(avr_platform_t *platform) {
	if (platform == NULL)
		return;

	platform->usage++;
}


/**
 * Unlock the platform. If it the last lock on the platform,
 * the platform is freed.
 * @param platform	Platform to unlock.
 */
void avr_unlock_platform(avr_platform_t *platform) {
	if (platform == NULL)
		return;

	/* unlock */
	if(--platform->usage != 0)
		return;

	/* destroy the modules */
	AVR_MEM_DESTROY(platform);
	AVR_GRT_DESTROY(platform);
	AVR_ERROR_DESTROY(platform);
	AVR_GEN_INT_DESTROY(platform);
	AVR_ENV_DESTROY(platform);
	AVR_LOADER_DESTROY(platform);
	AVR_CODE_DESTROY(platform);


	/* free the memories */
	avr_mem_delete(platform->mems.named.FLASH);
	avr_mem_delete(platform->mems.named.M);


	/* free system info */
	free(platform->sys_env);

	/* free the platform */
	free(platform);
	platform = NULL;
}


/* state management function */


/**
 * Create a new initialized state depending on a given platform
 * @param	platform	the platform helping the simulation on the created state
 * @return			a new initialized state suitable for the given platform
 */
avr_state_t *avr_new_state(avr_platform_t *platform)
{
	avr_state_t *state;

	/* allocation */
	state = (avr_state_t *)malloc(sizeof(avr_state_t));
	if(state == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* zeroing of all registers and memory references */
	memset(state, 0, sizeof(avr_state_t));

	/* creating platform */
	if(platform == NULL)
	{
		free(state);
		return NULL;
	}
	state->platform = platform;

	/* locking it */
	avr_lock_platform(state->platform);

	/* memory initialization */
	state->FLASH = state->platform->mems.named.FLASH;
	state->M = state->platform->mems.named.M;

	/* proper state initialization (from the op init) */
	AVR_SP = ((uint16_t)(1279LU));
	avr_mem_write8(AVR_M, (61 + 32), avr_field32(1279LU, 7, 0));
	avr_mem_write8(AVR_M, (62 + 32), avr_field32(1279LU, 15, 8));
	AVR_PC = ((uint16_t)(0));


	/* PC initialization */
	state->PC = platform->entry;
#	ifdef AVR_INIT_PC
		AVR_INIT_PC
#	else
		state->PC = platform->entry;
#	endif


	/* system registers initialization (argv, envp...) */
	avr_registers_fill_env(platform->sys_env, state);

	return state;
}


/**
 * Delete a state
 * @param	state	the state to delete
 */
void avr_delete_state(avr_state_t *state)
{
	if (state == NULL)
		return;

	/* unlock the platform */
	avr_unlock_platform(state->platform);

	/* free the state */
	free(state);
	state = NULL;
}


/**
 * Return a copy of a given state, both state will share the same memory
 * and each new state's register will have the same value as in the given state.
 * the copied state may not be suitable for further simulation as the stack pointers
 * and similar address registers will be identical in two different states
 * sharing the same memory
 *
 * @param	state	the state to copy
 * @return		a fresh allocated copy (to be freed by the caller)
 */
avr_state_t *avr_copy_state(avr_state_t *state)
{
	int i;

	if (state == NULL)
		return NULL;

	/* allocate a new state */
	avr_state_t *new_state = (avr_state_t *)malloc(sizeof(avr_state_t));
	if(new_state == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* copy the platform and lock it */
	/* !!WARNING!! is this needed? as we may not wish to simulate with this state */
	new_state->platform = state->platform;
	avr_lock_platform(new_state->platform);

	/* copy all the registers */
	new_state->SKIP_NEXT = state->SKIP_NEXT;
	new_state->SREG = state->SREG;
	for (i = 0; i < 64; i++)
		new_state->IO[i] = state->IO[i];
	new_state->SP = state->SP;
	for (i = 0; i < 32; i++)
		new_state->R[i] = state->R[i];
	new_state->PC = state->PC;

	/* copy the references to the memory */
	new_state->FLASH = state->FLASH;
	new_state->M = state->M;


	return new_state;
}


/**
 * Return a copy of a given state which will be intended for a further simulation,
 * both state will share the same memory
 * and each new state's register will have the same value as in the given state.
 *
 * TODO: we want to be able to simulate on this forked state
 * so we should really care about stack pointer and other address registers
 * used to write data in memory, these should have a different value
 * for each state created as we share the same memory
 *
 * @param	state	the state to fork
 * @return		a fresh allocated copy (to be freed by the caller)
 */
avr_state_t *avr_fork_state(avr_state_t *state)
{
	int i;

	if (state == NULL)
		return NULL;

	/* allocate a new state */
	avr_state_t *new_state = (avr_state_t *)malloc(sizeof(avr_state_t));
	if(new_state == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* copy the platform and lock it */
	new_state->platform = state->platform;
	avr_lock_platform(new_state->platform);

	/* copy all the registers */
	new_state->SKIP_NEXT = state->SKIP_NEXT;
	new_state->SREG = state->SREG;
	for (i = 0; i < 64; i++)
		new_state->IO[i] = state->IO[i];
	new_state->SP = state->SP;
	for (i = 0; i < 32; i++)
		new_state->R[i] = state->R[i];
	new_state->PC = state->PC;

	/* copy the references to the memory */
	new_state->FLASH = state->FLASH;
	new_state->M = state->M;

}


/**
 * Dump all register values of a given state to the given output
 *
 * @param	state	the state whose registers we wish to dump
 * @param	out	the file to dump within, typically stderr or stdout
 */
void avr_dump_state(avr_state_t *state, FILE *out)
{
	int i;

	/* dump all the registers */
	fprintf(out, "SKIP_NEXT = %02X\n", state->SKIP_NEXT);
	fprintf(out, "SREG = %02X\n", state->SREG);
	fprintf(out, "IO\n");
	for (i = 0; i < 64; i++) {
		fprintf(out, "\t[%d] = %02X", i, state->IO[i]);
		if(i % 4 == 3)
			fputc('\n', out);
	}
	if(i % 4 != 3)
		fputc('\n', out);
	fprintf(out, "SP = %04X\n", state->SP);
	fprintf(out, "R\n");
	for (i = 0; i < 32; i++) {
		fprintf(out, "\t[%d] = %02X", i, state->R[i]);
		if(i % 4 == 3)
			fputc('\n', out);
	}
	if(i % 4 != 3)
		fputc('\n', out);
	fprintf(out, "PC = %04X\n", state->PC);

}


/**
 * Output the header of a CSV validation output.
 * @param out	File to output to.
 */
void avr_output_header_valid(FILE *out) {
	fputs("# PC", out);

	fputc('\n', out);
}


/**
 * Output the given state for validation. The first column is the address
 * of the current instruction and next ones are the register.
 * @param state		State to dump.
 * @param out		File to output to.
 */
void avr_output_state_valid(avr_state_t *state, FILE *out) {

#	define GLISS_GET_I(v)	fprintf(out, "\t%08x", (v))
#	define GLISS_GET_L(v)	fprintf(out, "\t%016llx", (v))

	fprintf(out, "%08x", state->PC);

	fputc('\n', out);
}


/**
 * return a reference (a pointer in fact) towards the platform of a given state
 *
 * @param	state	the state we want to access the platform
 * @return		the address of the platform of the given state
 */
avr_platform_t *avr_platform(avr_state_t *state)
{
	if (state == NULL)
		return NULL;

	/* return the platform */
	return state->platform;
}


/* simulation functions */


/**
 * Create a new simulator structure with the given state
 * @param	state	the state on which we intend to simulate
 * @param	start_addr	the beginning of the execution (useful for executables compiled with no _start symbol),
 *				if null we leave the PC in its previous state given by the loader
 * @param	exit_addr	the explicitly given last instruction address to simulate, if null we will stop running in another way
 */
avr_sim_t *avr_new_sim(avr_state_t *state, avr_address_t start_addr, avr_address_t exit_addr)
{
	avr_sim_t *sim;

	if (state == NULL)
		return NULL;

	/* allocate a new simulator */
	sim = (avr_sim_t *)malloc(sizeof(avr_sim_t));
	if(sim == NULL)
	{
		errno = ENOMEM;
		return NULL;
	}

	/* link the state to the new simulator */
	sim->state = state;

	/* create a new decoder */
	sim->decoder = avr_new_decoder(avr_platform(state));
	if (sim->decoder == NULL)
		return NULL;
	sim->addr_exit = exit_addr;
	if (start_addr)
		sim->state->PC = start_addr;

	/* not ended at start */
	sim->ended = 0;
	return sim;
}


//======================================================================
#if !defined(AVR_TRACE_CACHE) && !defined(AVR_DTRACE_CACHE)

/**
 * Return the next instruction to be executed by the given simulator
 *
 * this instruction is pointed by the PC
 *
 * @param	sim	the simulator which we simulate within
 * @return		the next instruction to be executed, fully decoded
 */
avr_inst_t *avr_next_inst(avr_sim_t *sim)
{
	/* retrieving the instruction (which is allocated by the decoder) */
	/* we let the caller check for error */
	return avr_decode(sim->decoder, sim->state->PC);
}


/**
 * Execute the next instruction in the given simulator.
 * It doesn't check if we reached the last instruction, so it should be done
 * separately using the function avr_is_sim_ended
 * @param	sim	the simulator which we simulate within
 */
void avr_step(avr_sim_t *sim)
{
	avr_inst_t*  inst;
	avr_state_t* state = sim->state;

	/* retrieving next instruction */
    inst = avr_decode(sim->decoder, state->PC);

	/* execute it */

	avr_code_table[inst->ident](state, inst);

#ifndef AVR_INF_DECODE_CACHE
#ifndef AVR_FIXED_DECODE_CACHE
#ifndef AVR_LRU_DECODE_CACHE
    /* finally free it */
	avr_free_inst(inst);
#endif
#endif
#endif

	/* ended ? */
	if(sim->addr_exit == state->PC)
		sim->ended = 1;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs and count the number of executed instructions
 * until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * @return number of executed instructions
 * */
uint64_t avr_run_and_count_inst(avr_sim_t *sim)
{
	uint64_t i = 0;
    avr_state_t*   state     = sim->state;
    avr_decoder_t* decoder   = sim->decoder;
    avr_address_t  addr_exit = sim->addr_exit;
	avr_inst_t* inst;
	while(!sim->ended) {
		inst = avr_decode(decoder, state->PC);
		avr_code_table[inst->ident](state, inst);
#ifndef AVR_INF_DECODE_CACHE
#ifndef AVR_FIXED_DECODE_CACHE
#ifndef AVR_LRU_DECODE_CACHE
    /* finally free it */
	avr_free_inst(inst);
#endif
#endif
#endif
		i++;
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
	return i;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * */
void avr_run_sim(avr_sim_t *sim)
{
	avr_state_t*   state     = sim->state;
    avr_decoder_t* decoder   = sim->decoder;
    avr_address_t  addr_exit = sim->addr_exit;
	avr_inst_t* inst;
	while(!sim->ended) {
		inst = avr_decode(decoder, state->PC);
		avr_code_table[inst->ident](state, inst);
#ifndef AVR_INF_DECODE_CACHE
#ifndef AVR_FIXED_DECODE_CACHE
#ifndef AVR_LRU_DECODE_CACHE
    /* finally free it */
		avr_free_inst(inst);
#endif
#endif
#endif
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
}
#endif
//======================================================================
#ifdef AVR_TRACE_CACHE
/**
 * Return the next instruction to be executed by the given simulator
 *
 * this instruction is pointed by the PC
 *
 * @param	sim	the simulator which we simulate within
 * @return		the next instruction to be executed, fully decoded
 */
avr_inst_t *avr_next_inst(avr_sim_t *sim)
{
	/* retrieving the instruction (which is allocated by the decoder) */
	/* we let the caller check for error */
	return avr_decode(sim->decoder, sim->state->PC) + ((sim->state->NIA >> 2) & (TRACE_DEPTH-1));
}


/**
 * Execute the next instruction in the given simulator.
 * It doesn't check if we reached the last instruction, so it should be done
 * separately using the function avr_is_sim_ended
 * @param	sim	the simulator which we simulate within
 */
void avr_step(avr_sim_t *sim)
{
	avr_inst_t*  inst;
	avr_state_t* state = sim->state;

	/* retrieving next instruction */
    inst =  avr_decode(sim->decoder, state->PC) + ((sim->state->NIA >> 2) & (TRACE_DEPTH-1));

	/* execute it */

	avr_code_table[inst->ident](state, inst);

	/* ended ? */
	if(sim->addr_exit == state->PC)
		sim->ended = 1;
}


/**
 * Straightforward execution of the simulated programm.
 * It runs and count the number of executed instructions
 * until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * @return number of executed instructions
 * */
uint64_t avr_run_and_count_inst(avr_sim_t *sim)
{
	uint64_t i = 0;
    uint32_t num_bloc;
    avr_state_t*   state     = sim->state;
    avr_decoder_t* decoder   = sim->decoder;
    avr_address_t  addr_exit = sim->addr_exit;
    avr_inst_t*    inst, *trace;

	while(!sim->ended)
	{
        trace    = avr_decode(decoder, state->PC);
        num_bloc = (state->PC >> 2) >> TRACE_DEPTH_PW;

        while((((state->PC >> 2)>> TRACE_DEPTH_PW) == num_bloc) && (!sim->ended) && (addr_exit != state->PC))
        {
			inst = trace + ((state->NIA >> 2) & (TRACE_DEPTH-1));
			}
			i++;
		}

		/* ended ? */
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
	return i;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * */
void avr_run_sim(avr_sim_t *sim)
{
    uint32_t num_bloc;
    avr_state_t*   state     = sim->state;
    avr_decoder_t* decoder   = sim->decoder;
    avr_address_t  addr_exit = sim->addr_exit;
    avr_inst_t*    inst, *trace;

	while(addr_exit != state->PC)
	{
        trace    = avr_decode(decoder, state->PC);
        num_bloc = (state->PC >> 2) >> TRACE_DEPTH_PW;

        while((((state->PC >> 2)>> TRACE_DEPTH_PW) == num_bloc) && (addr_exit != state->PC))
        {
			inst = trace + ((state->NIA >> 2) & (TRACE_DEPTH-1));
		    avr_code_table[inst->ident](state, inst);
        }
	}
}
#endif
//======================================================================
#ifdef AVR_DTRACE_CACHE
/**
 * Return the next instruction to be executed by the given simulator
 *
 * this instruction is pointed by the PC
 *
 * @param	sim	the simulator which we simulate within
 * @return		the next instruction to be executed, fully decoded
 */
avr_inst_t *avr_next_inst(avr_sim_t *sim)
{
	/* retrieving the instruction (which is allocated by the decoder) */
	/* we let the caller check for error */

	/* Static variable is an optimisation hack
	 * in order to cache the current trace */
	static avr_inst_t*  inst = 0;
	avr_state_t* state = sim->state;

	/* retrieving next instruction */
	if(inst != 0)
	{
		inst++;
		if(inst->ident == -1)
			inst =  avr_decode(sim->decoder, state->PC);
	}else
	{
		inst =  avr_decode(sim->decoder, state->PC);
	}
	return inst;
}


/**
 * Execute the next instruction in the given simulator.
 * It doesn't check if we reached the last instruction, so it should be done
 * separately using the function avr_is_sim_ended
 * @param	sim	the simulator which we simulate within
 */
void avr_step(avr_sim_t *sim)
{
	/* Static variable is an optimisation hack
	 * in order to cache the current trace */
	static avr_inst_t*  inst = 0;
	avr_state_t* state = sim->state;

	/* retrieving next instruction */
	if(inst != 0)
	{
		inst++;
		if(inst->ident == -1)
			inst =  avr_decode(sim->decoder, state->PC);
	}else
	{
		inst =  avr_decode(sim->decoder, state->PC);
	}


	/* execute it */

	avr_code_table[inst->ident](state, inst);

		if(sim->addr_exit == state->PC)
			sim->ended = 1;
}


/**
 * Straightforward execution of the simulated programm.
 * It runs and count the number of executed instructions
 * until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * @return number of executed instructions
 * */
uint64_t avr_run_and_count_inst(avr_sim_t *sim)
{
	uint64_t i = 0;
    avr_state_t*   state     = sim->state;
    avr_decoder_t* decoder   = sim->decoder;
    avr_address_t  addr_exit = sim->addr_exit;
    avr_inst_t*    inst;

	while(!sim->ended)
	{
        inst = avr_decode(decoder, state->PC);

        while( (inst->ident != -1) && (!sim->ended) && (addr_exit != state->PC))
        {
		    avr_code_table[inst->ident](state, inst);
			inst++;
			i++;
        }

        /* ended ? */
		if(addr_exit == state->PC)
			sim->ended = 1;

	}
	return i;
}

/**
 * Straightforward execution of the simulated programm.
 * It runs until the programm reached the last instruction.
 * this is the <bold> fastest </bold> way to simulate a programm
 * @param	sim	the simulator which we simulate within
 * */
void avr_run_sim(avr_sim_t *sim)
{
    uint32_t num_bloc;
    avr_state_t*   state     = sim->state;
    avr_decoder_t* decoder   = sim->decoder;
    avr_address_t  addr_exit = sim->addr_exit;
    avr_inst_t*    inst;

	while(!sim->ended)
	{
        inst = avr_decode(decoder, state->PC);

        while( (inst->ident != -1) && (addr_exit != state->PC))
        {
		    avr_code_table[inst->ident](state, inst);
			inst++;
        }

        /* ended ? */
		if(addr_exit == state->PC)
			sim->ended = 1;
	}
}

#endif
//======================================================================
/**
 * @fn int avr_is_sim_ended(avr_sim_t *sim);
 * Indicate if the simulation is finished on the given simulator
 * @param	sim	the simulator which we simulate within
 * @return	whether or not the simulation is ended (0 => false, anything!=0 => true)
 */

/**
 * destruction of a simulator object, the associated state and decoder are also destroyed
 * @param	sim	the simulator to be deleted
 */
void avr_delete_sim(avr_sim_t *sim)
{
	if (sim == NULL)
		return;

	/* delete the decoder */
	avr_delete_decoder(sim->decoder);

	/* delete the state */
	avr_delete_state(sim->state);

	/* delete the sim */
	free(sim);
}


/**
 * Get the address of the next instruction to be executed,
 * indicated by PC
 * @param sim	Simulator to work with.
 * @return		Address of the current instruction.
 */
avr_address_t  avr_next_addr(avr_sim_t *sim) {
	assert(sim);
	return sim->state->PC;
}


/**
 * Set the address of the next instruction.
 * @param sim		Current simulator.
 * @param address	Next address.
 */
void avr_set_next_address(avr_sim_t *sim, avr_address_t address) {
	assert(sim);
	sim->state->PC = address;
}


/**
 * Set the exit address for simulation.
 * @param sim		Current simulator.
 * @param address	Exit address.
 */
void avr_set_exit_address(avr_sim_t *sim, avr_address_t address) {
	sim->addr_exit = address;
}


/**
 * Null-name ended list, provides the list of available decoding modes.
 */
avr_mode_t avr_modes[] = {
	{ "avr", avr_decode },
	{ 0, 0 }
};


/**
 * Boolean value indicating if assertion are tested are not.
 */
int avr_assert_enable = 1;


/**
 * Test the given assertion.
 * @param state	Current state.
 * @param cond	Condition of the assertion.
 * @param file	Source file of the assertion.
 * @param line	Source line of the assertion.
 */
void avr_assert(avr_state_t *state, int cond, const char *file, int line) {
	if(avr_assert_enable && !cond) {
		avr_dump_state(state, stderr);
		fprintf(stderr, "Assertion failure at %s:%d\n", file, line);
		abort();
	}
}


/****** convenience function only defined if a loader is available ******/

#ifdef AVR_LOADER_STATE
/**
 * Load the program from the given loader.
 * @param platform		Platform.
 * @param loader		Loader to get program from.
 */
void avr_load(avr_platform_t *platform, struct avr_loader_t *loader) {
	assert(platform);

	/* load in platform's memory */
	avr_loader_load(loader, platform);

	/* initialize system information */
	platform->entry = avr_loader_start(loader);
	avr_set_brk(platform, avr_brk_init(loader));

	/* !!TODO!! add argc,argv... init */
	/* stack initialization */
	avr_stack_fill_env(loader, platform, platform->sys_env);
}


/**
 * Load the given program in the platform and initialize stack
 * @param platform	Platform to load in.
 * @param path		Path of the file to load.
 * @return			0 for success, -1 for error (in errno).
 */
int avr_load_platform(avr_platform_t *platform, const char *path) {
	struct avr_loader_t *loader;
	assert(platform);

	/* open the file */
	loader = avr_loader_open(path);
	if(loader == NULL)
		return -1;

	/* load in platform's memory */
	avr_load(platform, loader);

	/* close the file */
	avr_loader_close(loader);

	/* return success */
	return 0;
}
#endif	/* AVR_LOADER_STATE */
