#!/bin/bash

function syntax {
	echo "SYNTAX: gliss-config [--cflags] [--libs]"
	echo "	--cflags -- output C flags"
	echo "	--libs -- output linked libraries"
}

while test "$1" != ""; do
	case "$1" in
		--cflags)
			echo "-I'/home/van3ll0pe/Documents/avr/core/include'"
			;;
        --libs)
        	echo "-L'/home/van3ll0pe/Documents/avr/core/src' -lavr       "
			;;
        --help|-h)
        		syntax
        		exit 0
                ;;
        *)
        		echo "ERROR: unknown option $1"
        		syntax
                exit 1
                ;;
        esac
        shift
done
