/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
#include <mos6502/fetch.h>
#include <mos6502/decode.h> /* api.h will be in it, for fetch functions, decode_table.h also */
#include <mos6502/config.h> /* for memory endiannesses */
#include <mos6502/code.h>

#include "code_table.h"


/**
 * Execute the given instruction in the given state.
 * @param state		Current execution state.
 * @param inst		Current instruction to execute.
 */
void mos6502_execute(mos6502_state_t *state, mos6502_inst_t *inst)
{
	mos6502_code_table[inst->ident](state, inst);
}


/* End of file mos6502_code.c */
