/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
#include <avr/fetch.h>
#include <avr/decode.h> /* api.h will be in it, for fetch functions, decode_table.h also */
#include <avr/config.h> /* for memory endiannesses */
#include <avr/code.h>

#include "code_table.h"


/**
 * Execute the given instruction in the given state.
 * @param state		Current execution state.
 * @param inst		Current instruction to execute.
 */
void avr_execute(avr_state_t *state, avr_inst_t *inst)
{
	avr_code_table[inst->ident](state, inst);
}


/* End of file avr_code.c */
