/* Generated by gep (125/05/23 10:52:00) copyright (c) 2011 IRIT - UPS */

#include <assert.h>
#include <mos6502/debug.h>
#include <mos6502/macros.h>
#include <mos6502/grt.h>

#define GLISS_IDX		idx
#define GLISS_I			r.iv
#define GLISS_L			r.lv
#define GLISS_F			r.fv
#define GLISS_D			r.dv
#define GLISS_GET_I(a)	r.iv = a
#define GLISS_GET_L(a)	r.lv = a
#define GLISS_GET_F(a)	r.fv = a
#define GLISS_GET_D(a)	r.dv = a

static register_bank_t mos6502_registers[] = {
	{
		1,
		"Y",
		"Y",
		1,
RTYPE_INT,
		8
	},
	{
		2,
		"total_cycle",
		"total_cycle",
		1,
RTYPE_INT,
		32
	},
	{
		4,
		"SR",
		"SR",
		1,
RTYPE_INT,
		8
	},
	{
		10,
		"is_jam",
		"is_jam",
		1,
RTYPE_INT,
		1
	},
	{
		11,
		"A",
		"A",
		1,
RTYPE_INT,
		8
	},
	{
		12,
		"SP",
		"SP",
		1,
RTYPE_INT,
		8
	},
	{
		14,
		"cycle",
		"cycle",
		1,
RTYPE_INT,
		32
	},
	{
		15,
		"X",
		"X",
		1,
RTYPE_INT,
		8
	},
	{
		16,
		"PC",
		"PC",
		1,
RTYPE_ADDR,
		16
	},
	{
		-1
	}
};


/**
 * Get the description of registers of the architecture.
 * @return		Array of registers (last one has a negative identifier).
 */
register_bank_t *mos6502_get_registers(void) {
	return mos6502_registers;
}

/**
 * Get the value of a register.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @return			Value of the register.
 */
register_value_t mos6502_get_register(mos6502_state_t *state, int id, int idx) {
	register_value_t r;
	switch(id) {
	case 1: {
				GLISS_GET_I(MOS6502_Y);

		} break;
	case 2: {
				GLISS_GET_I(MOS6502_TOTAL_CYCLE);

		} break;
	case 4: {
				GLISS_GET_I(MOS6502_SR);

		} break;
	case 10: {
				GLISS_GET_I(MOS6502_IS_JAM);

		} break;
	case 11: {
				GLISS_GET_I(MOS6502_A);

		} break;
	case 12: {
				GLISS_GET_I(MOS6502_SP);

		} break;
	case 14: {
				GLISS_GET_I(MOS6502_CYCLE);

		} break;
	case 15: {
				GLISS_GET_I(MOS6502_X);

		} break;
	case 16: {
				GLISS_GET_I(MOS6502_PC);

		} break;

	default:
		assert(0);
	}
	return r;
}


/**
 * Set the value of a register in the given state.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @param value		Value to put in register.
 */
void mos6502_set_register(mos6502_state_t *state, int id, int idx, register_value_t r) {
	switch(id) {
	case 1: {
				MOS6502_Y = GLISS_I;

		} break;
	case 2: {
				MOS6502_TOTAL_CYCLE = GLISS_I;

		} break;
	case 4: {
				MOS6502_SR = GLISS_I;

		} break;
	case 10: {
				MOS6502_IS_JAM = GLISS_I;

		} break;
	case 11: {
				MOS6502_A = GLISS_I;

		} break;
	case 12: {
				MOS6502_SP = GLISS_I;

		} break;
	case 14: {
				MOS6502_CYCLE = GLISS_I;

		} break;
	case 15: {
				MOS6502_X = GLISS_I;

		} break;
	case 16: {
				MOS6502_PC = GLISS_I;

		} break;

	default:
		assert(0);
	}
}


/* handle of exceptions */


/* list of exceptions */
static mos6502_exception_t exceptions[] = {
	{ 0, 0, 0 }
};


/**
 * Get the list of exceptions.
 * @return	List of exceptions ended by an item whose name is null.
 */
mos6502_exception_t *mos6502_exceptions(void) {
	return exceptions;
}

