/* Generated by gep (125/04/14 21:47:43) copyright (c) 2011 IRIT - UPS */

#include <assert.h>
#include <avr/debug.h>
#include <avr/macros.h>
#include <avr/grt.h>

#define GLISS_IDX		idx
#define GLISS_I			r.iv
#define GLISS_L			r.lv
#define GLISS_F			r.fv
#define GLISS_D			r.dv
#define GLISS_GET_I(a)	r.iv = a
#define GLISS_GET_L(a)	r.lv = a
#define GLISS_GET_F(a)	r.fv = a
#define GLISS_GET_D(a)	r.dv = a

static register_bank_t avr_registers[] = {
	{
		5,
		"SKIP_NEXT",
		"SKIP_NEXT",
		1,
RTYPE_INT,
		1
	},
	{
		6,
		"SREG",
		"SREG",
		1,
RTYPE_INT,
		8
	},
	{
		7,
		"IO",
		"IO%d",
		64,
RTYPE_INT,
		8
	},
	{
		11,
		"SP",
		"SP",
		1,
RTYPE_INT,
		16
	},
	{
		12,
		"R",
		"R%d",
		32,
RTYPE_INT,
		8
	},
	{
		14,
		"PC",
		"PC",
		1,
RTYPE_ADDR,
		16
	},
	{
		-1
	}
};


/**
 * Get the description of registers of the architecture.
 * @return		Array of registers (last one has a negative identifier).
 */
register_bank_t *avr_get_registers(void) {
	return avr_registers;
}

/**
 * Get the value of a register.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @return			Value of the register.
 */
register_value_t avr_get_register(avr_state_t *state, int id, int idx) {
	register_value_t r;
	switch(id) {
	case 5: {
				GLISS_GET_I(AVR_SKIP_NEXT);

		} break;
	case 6: {
				GLISS_GET_I(AVR_SREG);

		} break;
	case 7: {
				GLISS_GET_I(AVR_IO[GLISS_IDX]);

		} break;
	case 11: {
				GLISS_GET_I(AVR_SP);

		} break;
	case 12: {
				GLISS_GET_I(AVR_R[GLISS_IDX]);

		} break;
	case 14: {
				GLISS_GET_I(AVR_PC);

		} break;

	default:
		assert(0);
	}
	return r;
}


/**
 * Set the value of a register in the given state.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @param value		Value to put in register.
 */
void avr_set_register(avr_state_t *state, int id, int idx, register_value_t r) {
	switch(id) {
	case 5: {
				AVR_SKIP_NEXT = GLISS_I;

		} break;
	case 6: {
				AVR_SREG = GLISS_I;

		} break;
	case 7: {
				AVR_IO[GLISS_IDX] = GLISS_I;

		} break;
	case 11: {
				AVR_SP = GLISS_I;

		} break;
	case 12: {
				AVR_R[GLISS_IDX] = GLISS_I;

		} break;
	case 14: {
				AVR_PC = GLISS_I;

		} break;

	default:
		assert(0);
	}
}


/* handle of exceptions */


/* list of exceptions */
static avr_exception_t exceptions[] = {
	{ 0, 0, 0 }
};


/**
 * Get the list of exceptions.
 * @return	List of exceptions ended by an item whose name is null.
 */
avr_exception_t *avr_exceptions(void) {
	return exceptions;
}

