/* Generated by gep (125/04/14 21:47:46) copyright (c) 2008 IRIT - UPS */

#include <string.h>
#include <stdio.h>
#include <avr/api.h>
#include <avr/id.h>
#include <avr/macros.h>
#include <avr/grt.h>
#include "platform.h"


/* useful macros */
#define __GLISS_MASK32(n, e) ((n)==32 ? (e) : ((e) & ((1 << n) - 1)))
#define __GLISS_MASK64(n, e) ((n)==64 ? (e) : ((e) & ((1LL << n) - 1)))
#define __GLISS_EXTS(n, e) (((e) << n) >> n)



/**
 * Pointer allowing to change the way a label is solved.
 */
avr_label_solver_t avr_solve_label = avr_solve_label_null;


/**
 * Default label solver.
 * @param address	Address to look a label for.
 * @return			Buffer to solved label (may be destroyed between two calls to this function).
 */
char *avr_solve_label_null(avr_address_t address) {
	static char buf[10];
	sprintf(buf, "%08x", address);
	return buf;
}

typedef void (*disasm_t)(char *buffer, avr_inst_t *inst);

/* functions */
static void disasm_unknown(char *buffer, avr_inst_t *inst) {
	strcpy(buffer, "<unknown>");
}

static void disasm_CALL_D__LP_04X_RP_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CALL %u (%04x)", (((uint32_t)(AVR_CALL_D__LP_04X_RP__x_x_k)) * 2), ((AVR_CALL_D__LP_04X_RP____IADDR + (((uint32_t)(AVR_CALL_D__LP_04X_RP__x_x_k)) * 2)) + 2));

}
static void disasm_JMP_D__LP_04X_RP_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "JMP %u (%04x)", (((uint32_t)(AVR_JMP_D__LP_04X_RP__x_x_k)) * 2), ((AVR_JMP_D__LP_04X_RP____IADDR + (((uint32_t)(AVR_JMP_D__LP_04X_RP__x_x_k)) * 2)) + 2));

}
static void disasm_STS_D__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "STS %d, R%d", AVR_STS_D__RD_x_x_a, AVR_STS_D__RD_x_x_d);

}
static void disasm_LDS_RD__0X04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDS R%d, 0x%04x", AVR_LDS_RD__0X04X_x_x_d, AVR_LDS_RD__0X04X_x_x_k);

}
static void disasm_BRID___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRID .%+d ; %+04x", (((int32_t)(AVR_BRID___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRID___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRID___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRIE___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRIE .%+d ; %+04x", (((int32_t)(AVR_BRIE___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRIE___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRIE___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRVC___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRVC .%+d ; %+04x", (((int32_t)(AVR_BRVC___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRVC___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRVC___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRVS___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRVS .%+d ; %+04x", (((int32_t)(AVR_BRVS___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRVS___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRVS___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRTC___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRTC .%+d ; %+04x", (((int32_t)(AVR_BRTC___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRTC___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRTC___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRTS___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRTS .%+d ; %+04x", (((int32_t)(AVR_BRTS___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRTS___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRTS___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRHC___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRHC .%+d ; %+04x", (((int32_t)(AVR_BRHC___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRHC___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRHC___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRHS___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRHS .%+d ; %+04x", (((int32_t)(AVR_BRHS___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRHS___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRHS___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRLT___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRLT .%+d ; %+04x", (((int32_t)(AVR_BRLT___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRLT___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRLT___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRGE___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRGE .%+d ; %+04x", (((int32_t)(AVR_BRGE___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRGE___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRGE___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRPL___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRPL .%+d ; %+04x", (((int32_t)(AVR_BRPL___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRPL___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRPL___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRMI___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRMI .%+d ; %+04x", (((int32_t)(AVR_BRMI___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRMI___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRMI___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRCC___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRCC .%+d ; %+04x", (((int32_t)(AVR_BRCC___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRCC___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRCC___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRCS___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRCS .%+d ; %+04x", (((int32_t)(AVR_BRCS___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRCS___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRCS___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BRNE___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BRNE .%+d ; %+04x", (((int32_t)(AVR_BRNE___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BRNE___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BRNE___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_BREQ___P_D__3B__P_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BREQ .%+d ; %+04x", (((int32_t)(AVR_BREQ___P_D__3B__P_04X_x_x_k)) * 2), (((int32_t)((AVR_BREQ___P_D__3B__P_04X___IADDR + 2))) + (((int32_t)(AVR_BREQ___P_D__3B__P_04X_x_x_k)) * 2)));

}
static void disasm_SBIC_IOD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBIC IO%d, %d", AVR_SBIC_IOD__D_x_x_a, AVR_SBIC_IOD__D_x_x_b);

}
static void disasm_SBIC_IOD__D_0(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBIC IO%d, %d", AVR_SBIC_IOD__D_0_x_x_a, AVR_SBIC_IOD__D_0_x_x_b);

}
static void disasm_SBRS_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBRS R%d, %d", AVR_SBRS_RD__D_x_x_r, AVR_SBRS_RD__D_x_x_b);

}
static void disasm_SBRC_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBRC R%d, %d", AVR_SBRC_RD__D_x_x_r, AVR_SBRC_RD__D_x_x_b);

}
static void disasm_CPI_RD__0X02X__3B_D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPI R%u, 0x%02x ; %d", (((uint32_t)(AVR_CPI_RD__0X02X__3B_D_x_x_d)) + 16), AVR_CPI_RD__0X02X__3B_D_x_x_k, AVR_CPI_RD__0X02X__3B_D_x_x_k);

}
static void disasm_CPC_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPC R%d, R%d", AVR_CPC_RD__RD_x_x_d, AVR_CPC_RD__RD_x_x_r);

}
static void disasm_CP_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CP R%d, R%d", AVR_CP_RD__RD_x_x_d, AVR_CP_RD__RD_x_x_r);

}
static void disasm_CSPE_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CSPE R%d, R%d", AVR_CSPE_RD__RD_x_x_d, AVR_CSPE_RD__RD_x_x_r);

}
static void disasm_RETI(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "RETI");

}
static void disasm_RET(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "RET");

}
static void disasm_ICALL(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ICALL");

}
static void disasm_RCALL_D__LP_04X_RP_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "RCALL %d (%04x)", (((int32_t)(AVR_RCALL_D__LP_04X_RP__x_x_k)) * 2), ((((int32_t)(AVR_RCALL_D__LP_04X_RP____IADDR)) + (((int32_t)(AVR_RCALL_D__LP_04X_RP__x_x_k)) * 2)) + 2));

}
static void disasm_IJMP(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "IJMP");

}
static void disasm_RJMP___P_D__3B_04X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "RJMP .%+d ; %04x", (((int32_t)(AVR_RJMP___P_D__3B_04X_x_x_k)) * 2), ((((int32_t)(AVR_RJMP___P_D__3B_04X___IADDR)) + (((int32_t)(AVR_RJMP___P_D__3B_04X_x_x_k)) * 2)) + 2));

}
static void disasm_FMULSU_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "FMULSU R%u, R%u", (16 + ((uint32_t)(AVR_FMULSU_RD__RD_x_x_d))), (16 + ((uint32_t)(AVR_FMULSU_RD__RD_x_x_r))));

}
static void disasm_FMULS_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "FMULS R%u, R%u", (16 + ((uint32_t)(AVR_FMULS_RD__RD_x_x_d))), (16 + ((uint32_t)(AVR_FMULS_RD__RD_x_x_r))));

}
static void disasm_FMUL_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "FMUL R%u, R%u", (16 + ((uint32_t)(AVR_FMUL_RD__RD_x_x_d))), (16 + ((uint32_t)(AVR_FMUL_RD__RD_x_x_r))));

}
static void disasm_MULSU_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "MULSU R%u, R%u", (16 + ((uint32_t)(AVR_MULSU_RD__RD_x_x_d))), (16 + ((uint32_t)(AVR_MULSU_RD__RD_x_x_r))));

}
static void disasm_MULS_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "MULS R%u, R%u", (16 + ((uint32_t)(AVR_MULS_RD__RD_x_x_d))), (16 + ((uint32_t)(AVR_MULS_RD__RD_x_x_r))));

}
static void disasm_MUL_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "MUL R%d, R%d", AVR_MUL_RD__RD_x_x_d, AVR_MUL_RD__RD_x_x_r);

}
static void disasm_DEC_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEC R%d", AVR_DEC_RD_x_x_d);

}
static void disasm_INC_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "INC R%d", AVR_INC_RD_x_x_d);

}
static void disasm_NEG_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "NEG R%d", AVR_NEG_RD_x_x_d);

}
static void disasm_COM_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "COM R%d", AVR_COM_RD_x_x_d);

}
static void disasm_EOR_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR R%d, R%d", AVR_EOR_RD__RD_x_x_d, AVR_EOR_RD__RD_x_x_r);

}
static void disasm_ORI_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORI R%u, %d", (16 + ((uint32_t)(AVR_ORI_RD__D_x_x_d))), AVR_ORI_RD__D_x_x_k);

}
static void disasm_OR_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "OR R%d, R%d", AVR_OR_RD__RD_x_x_d, AVR_OR_RD__RD_x_x_r);

}
static void disasm_ANDI_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ANDI R%u, R%d", (16 + ((uint32_t)(AVR_ANDI_RD__RD_x_x_d))), AVR_ANDI_RD__RD_x_x_k);

}
static void disasm_AND_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND R%d, R%d", AVR_AND_RD__RD_x_x_d, AVR_AND_RD__RD_x_x_r);

}
static void disasm_SBIW_RD_3ARD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBIW R%u:R%u, %d", ((24 + (((uint32_t)(AVR_SBIW_RD_3ARD__D_x_x_d)) * 2)) + 1), (24 + (((uint32_t)(AVR_SBIW_RD_3ARD__D_x_x_d)) * 2)), AVR_SBIW_RD_3ARD__D_x_x_k);

}
static void disasm_SBCI_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBCI R%u, %d", (16 + ((uint32_t)(AVR_SBCI_RD__D_x_x_d))), AVR_SBCI_RD__D_x_x_k);

}
static void disasm_SBC_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC R%d, R%d", AVR_SBC_RD__RD_x_x_d, AVR_SBC_RD__RD_x_x_r);

}
static void disasm_SUBI_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SUBI R%u, %d", (16 + ((uint32_t)(AVR_SUBI_RD__D_x_x_d))), AVR_SUBI_RD__D_x_x_k);

}
static void disasm_SUB_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SUB R%d, R%d", AVR_SUB_RD__RD_x_x_d, AVR_SUB_RD__RD_x_x_r);

}
static void disasm_ADIW_RD_3ARD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADIW R%u:R%u, %d", ((24 + (((uint32_t)(AVR_ADIW_RD_3ARD__D_x_x_d)) * 2)) + 1), (24 + (((uint32_t)(AVR_ADIW_RD_3ARD__D_x_x_d)) * 2)), AVR_ADIW_RD_3ARD__D_x_x_k);

}
static void disasm_ADC_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC R%d, R%d", AVR_ADC_RD__RD_x_x_d, AVR_ADC_RD__RD_x_x_r);

}
static void disasm_ADD_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADD R%d, R%d", AVR_ADD_RD__RD_x_x_d, AVR_ADD_RD__RD_x_x_r);

}
static void disasm_CBI_IOD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CBI IO%d, %d", AVR_CBI_IOD__D_x_x_a, AVR_CBI_IOD__D_x_x_b);

}
static void disasm_SBI_IOD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBI IO%d, %d", AVR_SBI_IOD__D_x_x_a, AVR_SBI_IOD__D_x_x_b);

}
static void disasm_CLH(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLH");

}
static void disasm_SEH(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEH");

}
static void disasm_CLT(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLT");

}
static void disasm_SET(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SET");

}
static void disasm_CLV(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLV");

}
static void disasm_SEV(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEV");

}
static void disasm_CLS(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLS");

}
static void disasm_SES(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SES");

}
static void disasm_CLI(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLI");

}
static void disasm_SEI(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEI");

}
static void disasm_CLZ(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLZ");

}
static void disasm_SEZ(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEZ");

}
static void disasm_CLN(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLN");

}
static void disasm_SEN(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEN");

}
static void disasm_CLC(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLC");

}
static void disasm_SEC(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEC");

}
static void disasm_BST_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BST R%d, %d", AVR_BST_RD__D_x_x_d, AVR_BST_RD__D_x_x_b);

}
static void disasm_BLD_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "BLD R%d, %d", AVR_BLD_RD__D_x_x_d, AVR_BLD_RD__D_x_x_b);

}
static void disasm_SWAP_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "SWAP R%d", AVR_SWAP_RD_x_x_d);

}
static void disasm_ASR_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ASR R%d", AVR_ASR_RD_x_x_d);

}
static void disasm_ROR_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROR R%d", AVR_ROR_RD_x_x_d);

}
static void disasm_LSR_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LSR R%d", AVR_LSR_RD_x_x_d);

}
static void disasm_LPM_RD__Z_P_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LPM R%d, Z+", AVR_LPM_RD__Z_P__x_x_d);

}
static void disasm_LPM_RD__Z(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LPM R%d, Z", AVR_LPM_RD__Z_x_x_d);

}
static void disasm_LPM(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LPM");

}
static void disasm_LAC_Z__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAC Z, R%d", AVR_LAC_Z__RD_x_x_d);

}
static void disasm_LAT_Z__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAT Z, R%d", AVR_LAT_Z__RD_x_x_d);

}
static void disasm_LAS_Z__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAS Z, R%d", AVR_LAS_Z__RD_x_x_d);

}
static void disasm_XCH_Z__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "XCH Z, R%d", AVR_XCH_Z__RD_x_x_d);

}
static void disasm_POP_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "POP R%d", AVR_POP_RD_x_x_d);

}
static void disasm_PUSH_RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "PUSH R%d", AVR_PUSH_RD_x_x_d);

}
static void disasm_OUT_D__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "OUT %d, R%d", AVR_OUT_D__RD_x_x_a, AVR_OUT_D__RD_x_x_d);

}
static void disasm_IN_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "IN R%d, %d", AVR_IN_RD__D_x_x_d, AVR_IN_RD__D_x_x_a);

}
static void disasm_ST_Z_P___RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST Z+, R%d", AVR_ST_Z_P___RD_x_x_d);

}
static void disasm_ST__M_Z__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST -Z, R%d", AVR_ST__M_Z__RD_x_x_d);

}
static void disasm_STD_Z_P_D__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "STD Z+%d, R%d", AVR_STD_Z_P_D__RD_x_x_q, AVR_STD_Z_P_D__RD_x_x_d);

}
static void disasm_ST_Y_P___RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST Y+, R%d", AVR_ST_Y_P___RD_x_x_d);

}
static void disasm_ST__M_Y__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST -Y, R%d", AVR_ST__M_Y__RD_x_x_d);

}
static void disasm_STD_Y_P_D__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "STD Y+%d, R%d", AVR_STD_Y_P_D__RD_x_x_q, AVR_STD_Y_P_D__RD_x_x_d);

}
static void disasm_ST_X_P___RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST X+, R%d", AVR_ST_X_P___RD_x_x_d);

}
static void disasm_ST__M_X__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST -X, R%d", AVR_ST__M_X__RD_x_x_d);

}
static void disasm_ST_X__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "ST X, R%d", AVR_ST_X__RD_x_x_d);

}
static void disasm_LDD_RD__Z_P_D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDD R%d, Z+%d", AVR_LDD_RD__Z_P_D_x_x_d, AVR_LDD_RD__Z_P_D_x_x_q);

}
static void disasm_LD_RD___M_Z(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, -Z", AVR_LD_RD___M_Z_x_x_d);

}
static void disasm_LD_RD__Z_P_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, Z+", AVR_LD_RD__Z_P__x_x_d);

}
static void disasm_LDD_RD__Y_P_D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDD R%d, Y+%d", AVR_LDD_RD__Y_P_D_x_x_d, AVR_LDD_RD__Y_P_D_x_x_q);

}
static void disasm_LD_RD___M_Y(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, -Y", AVR_LD_RD___M_Y_x_x_d);

}
static void disasm_LD_RD__Y_P_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, Y+", AVR_LD_RD__Y_P__x_x_d);

}
static void disasm_LD_RD___M_X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, -X", AVR_LD_RD___M_X_x_x_d);

}
static void disasm_LD_RD__X_P_(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, X+", AVR_LD_RD__X_P__x_x_d);

}
static void disasm_LD_RD__X(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LD R%d, X", AVR_LD_RD__X_x_x_d);

}
static void disasm_MOVW_RD_3AD__RD_3AD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "MOVW R%u:%d, R%u:%d", (((uint32_t)(AVR_MOVW_RD_3AD__RD_3AD_x_x_d)) + 1), AVR_MOVW_RD_3AD__RD_3AD_x_x_d, (((uint32_t)(AVR_MOVW_RD_3AD__RD_3AD_x_x_r)) + 1), AVR_MOVW_RD_3AD__RD_3AD_x_x_r);

}
static void disasm_MOV_RD__RD(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "MOV R%d, R%d", AVR_MOV_RD__RD_x_x_d, AVR_MOV_RD__RD_x_x_r);

}
static void disasm_LDI_RD__D(char *__buffer, avr_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDI R%u, %d", (((uint32_t)(AVR_LDI_RD__D_x_x_d)) + 16), AVR_LDI_RD__D_x_x_k);

}


/* table */
static disasm_t disasm_tab[] = {
	disasm_unknown,
	disasm_CALL_D__LP_04X_RP_,
	disasm_JMP_D__LP_04X_RP_,
	disasm_STS_D__RD,
	disasm_LDS_RD__0X04X,
	disasm_BRID___P_D__3B__P_04X,
	disasm_BRIE___P_D__3B__P_04X,
	disasm_BRVC___P_D__3B__P_04X,
	disasm_BRVS___P_D__3B__P_04X,
	disasm_BRTC___P_D__3B__P_04X,
	disasm_BRTS___P_D__3B__P_04X,
	disasm_BRHC___P_D__3B__P_04X,
	disasm_BRHS___P_D__3B__P_04X,
	disasm_BRLT___P_D__3B__P_04X,
	disasm_BRGE___P_D__3B__P_04X,
	disasm_BRPL___P_D__3B__P_04X,
	disasm_BRMI___P_D__3B__P_04X,
	disasm_BRCC___P_D__3B__P_04X,
	disasm_BRCS___P_D__3B__P_04X,
	disasm_BRNE___P_D__3B__P_04X,
	disasm_BREQ___P_D__3B__P_04X,
	disasm_SBIC_IOD__D,
	disasm_SBIC_IOD__D_0,
	disasm_SBRS_RD__D,
	disasm_SBRC_RD__D,
	disasm_CPI_RD__0X02X__3B_D,
	disasm_CPC_RD__RD,
	disasm_CP_RD__RD,
	disasm_CSPE_RD__RD,
	disasm_RETI,
	disasm_RET,
	disasm_ICALL,
	disasm_RCALL_D__LP_04X_RP_,
	disasm_IJMP,
	disasm_RJMP___P_D__3B_04X,
	disasm_FMULSU_RD__RD,
	disasm_FMULS_RD__RD,
	disasm_FMUL_RD__RD,
	disasm_MULSU_RD__RD,
	disasm_MULS_RD__RD,
	disasm_MUL_RD__RD,
	disasm_DEC_RD,
	disasm_INC_RD,
	disasm_NEG_RD,
	disasm_COM_RD,
	disasm_EOR_RD__RD,
	disasm_ORI_RD__D,
	disasm_OR_RD__RD,
	disasm_ANDI_RD__RD,
	disasm_AND_RD__RD,
	disasm_SBIW_RD_3ARD__D,
	disasm_SBCI_RD__D,
	disasm_SBC_RD__RD,
	disasm_SUBI_RD__D,
	disasm_SUB_RD__RD,
	disasm_ADIW_RD_3ARD__D,
	disasm_ADC_RD__RD,
	disasm_ADD_RD__RD,
	disasm_CBI_IOD__D,
	disasm_SBI_IOD__D,
	disasm_CLH,
	disasm_SEH,
	disasm_CLT,
	disasm_SET,
	disasm_CLV,
	disasm_SEV,
	disasm_CLS,
	disasm_SES,
	disasm_CLI,
	disasm_SEI,
	disasm_CLZ,
	disasm_SEZ,
	disasm_CLN,
	disasm_SEN,
	disasm_CLC,
	disasm_SEC,
	disasm_BST_RD__D,
	disasm_BLD_RD__D,
	disasm_SWAP_RD,
	disasm_ASR_RD,
	disasm_ROR_RD,
	disasm_LSR_RD,
	disasm_LPM_RD__Z_P_,
	disasm_LPM_RD__Z,
	disasm_LPM,
	disasm_LAC_Z__RD,
	disasm_LAT_Z__RD,
	disasm_LAS_Z__RD,
	disasm_XCH_Z__RD,
	disasm_POP_RD,
	disasm_PUSH_RD,
	disasm_OUT_D__RD,
	disasm_IN_RD__D,
	disasm_ST_Z_P___RD,
	disasm_ST__M_Z__RD,
	disasm_STD_Z_P_D__RD,
	disasm_ST_Y_P___RD,
	disasm_ST__M_Y__RD,
	disasm_STD_Y_P_D__RD,
	disasm_ST_X_P___RD,
	disasm_ST__M_X__RD,
	disasm_ST_X__RD,
	disasm_LDD_RD__Z_P_D,
	disasm_LD_RD___M_Z,
	disasm_LD_RD__Z_P_,
	disasm_LDD_RD__Y_P_D,
	disasm_LD_RD___M_Y,
	disasm_LD_RD__Y_P_,
	disasm_LD_RD___M_X,
	disasm_LD_RD__X_P_,
	disasm_LD_RD__X,
	disasm_MOVW_RD_3AD__RD_3AD,
	disasm_MOV_RD__RD,
	disasm_LDI_RD__D
};

/**
 * Disassemble the given instruction.
 * @param buffer	Buffer to write in.
 * @param inst		Decode instruction.
 */
void avr_disasm(char *buffer, avr_inst_t *inst) {
	disasm_tab[inst->ident](buffer, inst);
}
