/* Generated by gep (125/05/23 10:50:24) copyright (c) 2008 IRIT - UPS */

#include <string.h>
#include <stdio.h>
#include <mos6502/api.h>
#include <mos6502/id.h>
#include <mos6502/macros.h>
#include <mos6502/grt.h>
#include "platform.h"


/* useful macros */
#define __GLISS_MASK32(n, e) ((n)==32 ? (e) : ((e) & ((1 << n) - 1)))
#define __GLISS_MASK64(n, e) ((n)==64 ? (e) : ((e) & ((1LL << n) - 1)))
#define __GLISS_EXTS(n, e) (((e) << n) >> n)



/**
 * Pointer allowing to change the way a label is solved.
 */
mos6502_label_solver_t mos6502_solve_label = mos6502_solve_label_null;


/**
 * Default label solver.
 * @param address	Address to look a label for.
 * @return			Buffer to solved label (may be destroyed between two calls to this function).
 */
char *mos6502_solve_label_null(mos6502_address_t address) {
	static char buf[10];
	sprintf(buf, "%08x", address);
	return buf;
}

typedef void (*disasm_t)(char *buffer, mos6502_inst_t *inst);

/* functions */
static void disasm_unknown(char *buffer, mos6502_inst_t *inst) {
	strcpy(buffer, "<unknown>");
}

static void disasm_JAM(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_1(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_2(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_3(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_4(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_5(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_6(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_7(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_8(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_9(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_JAM_10(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JAM");

}
static void disasm_IGN__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x, X", MOS6502_IGN__242X__X_x_address_lo);

}
static void disasm_IGN__242X__X_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x, X", MOS6502_IGN__242X__X_0_x_address_lo);

}
static void disasm_IGN__242X__X_1(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x, X", MOS6502_IGN__242X__X_1_x_address_lo);

}
static void disasm_IGN__242X__X_2(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x, X", MOS6502_IGN__242X__X_2_x_address_lo);

}
static void disasm_IGN__242X__X_3(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x, X", MOS6502_IGN__242X__X_3_x_address_lo);

}
static void disasm_IGN__242X__X_4(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x, X", MOS6502_IGN__242X__X_4_x_address_lo);

}
static void disasm_IGN__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x", MOS6502_IGN__242X_x_address_lo);

}
static void disasm_IGN__242X_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x", MOS6502_IGN__242X_0_x_address_lo);

}
static void disasm_IGN__242X_1(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x", MOS6502_IGN__242X_1_x_address_lo);

}
static void disasm_IGN__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x, X", MOS6502_IGN__242X2X__X_x_address_hi, MOS6502_IGN__242X2X__X_x_address_lo);

}
static void disasm_IGN__242X2X__X_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x, X", MOS6502_IGN__242X2X__X_0_x_address_hi, MOS6502_IGN__242X2X__X_0_x_address_lo);

}
static void disasm_IGN__242X2X__X_1(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x, X", MOS6502_IGN__242X2X__X_1_x_address_hi, MOS6502_IGN__242X2X__X_1_x_address_lo);

}
static void disasm_IGN__242X2X__X_2(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x, X", MOS6502_IGN__242X2X__X_2_x_address_hi, MOS6502_IGN__242X2X__X_2_x_address_lo);

}
static void disasm_IGN__242X2X__X_3(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x, X", MOS6502_IGN__242X2X__X_3_x_address_hi, MOS6502_IGN__242X2X__X_3_x_address_lo);

}
static void disasm_IGN__242X2X__X_4(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x, X", MOS6502_IGN__242X2X__X_4_x_address_hi, MOS6502_IGN__242X2X__X_4_x_address_lo);

}
static void disasm_IGN__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "IGN $%2x%2x", MOS6502_IGN__242X2X_x_address_hi, MOS6502_IGN__242X2X_x_address_lo);

}
static void disasm_SKB__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SKB #%2x", MOS6502_SKB__I2X_x_value);

}
static void disasm_SKB__I2X_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SKB #%2x", MOS6502_SKB__I2X_0_x_value);

}
static void disasm_SKB__I2X_1(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SKB #%2x", MOS6502_SKB__I2X_1_x_value);

}
static void disasm_SKB__I2X_2(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SKB #%2x", MOS6502_SKB__I2X_2_x_value);

}
static void disasm_SKB__I2X_3(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SKB #%2x", MOS6502_SKB__I2X_3_x_value);

}
static void disasm_NOP(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_NOP_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_NOP_1(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_NOP_2(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_NOP_3(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_NOP_4(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_USBC__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "USBC #%2x", MOS6502_USBC__I2X_x_value);

}
static void disasm_SLO__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO ($%2x), Y", MOS6502_SLO__LP__242X_RP___Y_x_address_lo);

}
static void disasm_SLO__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO ($%2x, X)", MOS6502_SLO__LP__242X__X_RP__x_address_lo);

}
static void disasm_SLO__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO $%2x%2x, Y", MOS6502_SLO__242X2X__Y_x_address_hi, MOS6502_SLO__242X2X__Y_x_address_lo);

}
static void disasm_SLO__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO $%2x%2x, X", MOS6502_SLO__242X2X__X_x_address_hi, MOS6502_SLO__242X2X__X_x_address_lo);

}
static void disasm_SLO__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO $%2x%2x", MOS6502_SLO__242X2X_x_address_hi, MOS6502_SLO__242X2X_x_address_lo);

}
static void disasm_SLO__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO $%2x, X", MOS6502_SLO__242X__X_x_address_lo);

}
static void disasm_SLO__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SLO $%2x", MOS6502_SLO__242X_x_address_lo);

}
static void disasm_RLA__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA ($%2x), Y", MOS6502_RLA__LP__242X_RP___Y_x_address_lo);

}
static void disasm_RLA__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA ($%2x, X)", MOS6502_RLA__LP__242X__X_RP__x_address_lo);

}
static void disasm_RLA__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA $%2x%2x, Y", MOS6502_RLA__242X2X__Y_x_address_hi, MOS6502_RLA__242X2X__Y_x_address_lo);

}
static void disasm_RLA__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA $%2x%2x, X", MOS6502_RLA__242X2X__X_x_address_hi, MOS6502_RLA__242X2X__X_x_address_lo);

}
static void disasm_RLA__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA $%2x%2x", MOS6502_RLA__242X2X_x_address_hi, MOS6502_RLA__242X2X_x_address_lo);

}
static void disasm_RLA__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA $%2x, X", MOS6502_RLA__242X__X_x_address_lo);

}
static void disasm_RLA__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RLA $%2x", MOS6502_RLA__242X_x_address_lo);

}
static void disasm_RRA__LP__242X_RP__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA ($%2x),Y", MOS6502_RRA__LP__242X_RP__Y_x_address_lo);

}
static void disasm_RRA__LP__242X_X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA ($%2x,X)", MOS6502_RRA__LP__242X_X_RP__x_address_lo);

}
static void disasm_RRA__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA $%2x%2x, Y", MOS6502_RRA__242X2X__Y_x_address_hi, MOS6502_RRA__242X2X__Y_x_address_lo);

}
static void disasm_RRA__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA $%2x%2x, X", MOS6502_RRA__242X2X__X_x_address_hi, MOS6502_RRA__242X2X__X_x_address_lo);

}
static void disasm_RRA__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA $%2x%2x", MOS6502_RRA__242X2X_x_address_hi, MOS6502_RRA__242X2X_x_address_lo);

}
static void disasm_RRA__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA $%2x, X", MOS6502_RRA__242X__X_x_address_lo);

}
static void disasm_RRA__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RRA $%2x", MOS6502_RRA__242X_x_address_lo);

}
static void disasm_SRE__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE ($%2x), Y", MOS6502_SRE__LP__242X_RP___Y_x_address_lo);

}
static void disasm_SRE__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE ($%2x, X)", MOS6502_SRE__LP__242X__X_RP__x_address_lo);

}
static void disasm_SRE__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE $%2x%2x, Y", MOS6502_SRE__242X2X__Y_x_address_hi, MOS6502_SRE__242X2X__Y_x_address_lo);

}
static void disasm_SRE__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE $%2x%2x, X", MOS6502_SRE__242X2X__X_x_address_hi, MOS6502_SRE__242X2X__X_x_address_lo);

}
static void disasm_SRE__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE $%2x%2x", MOS6502_SRE__242X2X_x_address_hi, MOS6502_SRE__242X2X_x_address_lo);

}
static void disasm_SRE__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE $%2x, X", MOS6502_SRE__242X__X_x_address_lo);

}
static void disasm_SRE__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SRE $%2x", MOS6502_SRE__242X_x_address_lo);

}
static void disasm_ISC__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC ($%2x), Y", MOS6502_ISC__LP__242X_RP___Y_x_address_lo);

}
static void disasm_ISC__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC ($%2x, X)", MOS6502_ISC__LP__242X__X_RP__x_address_lo);

}
static void disasm_ISC__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC $%2x%2x, Y", MOS6502_ISC__242X2X__Y_x_address_hi, MOS6502_ISC__242X2X__Y_x_address_lo);

}
static void disasm_ISC__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC $%2x%2x, X", MOS6502_ISC__242X2X__X_x_address_hi, MOS6502_ISC__242X2X__X_x_address_lo);

}
static void disasm_ISC__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC $%2x%2x", MOS6502_ISC__242X2X_x_address_hi, MOS6502_ISC__242X2X_x_address_lo);

}
static void disasm_ISC__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC $%2x, X", MOS6502_ISC__242X__X_x_address_lo);

}
static void disasm_ISC__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ISC $%2x", MOS6502_ISC__242X_x_address_lo);

}
static void disasm_DCP__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP ($%2x), Y", MOS6502_DCP__LP__242X_RP___Y_x_address_lo);

}
static void disasm_DCP__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP ($%2x, X)", MOS6502_DCP__LP__242X__X_RP__x_address_lo);

}
static void disasm_DCP__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP $%2x%2x, Y", MOS6502_DCP__242X2X__Y_x_address_hi, MOS6502_DCP__242X2X__Y_x_address_lo);

}
static void disasm_DCP__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP $%2x%2x, X", MOS6502_DCP__242X2X__X_x_address_hi, MOS6502_DCP__242X2X__X_x_address_lo);

}
static void disasm_DCP__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP $%2x%2x", MOS6502_DCP__242X2X_x_address_hi, MOS6502_DCP__242X2X_x_address_lo);

}
static void disasm_DCP__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP $%2x, X", MOS6502_DCP__242X__X_x_address_lo);

}
static void disasm_DCP__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DCP $%2x", MOS6502_DCP__242X_x_address_lo);

}
static void disasm_SHA__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SHA ($%2x), Y", MOS6502_SHA__LP__242X_RP___Y_x_address_lo);

}
static void disasm_SHA__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SHA $%2x%2x", MOS6502_SHA__242X2X_x_address_hi, MOS6502_SHA__242X2X_x_address_lo);

}
static void disasm_SHY__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SHY $%2x%2x", MOS6502_SHY__242X2X_x_address_hi, MOS6502_SHY__242X2X_x_address_lo);

}
static void disasm_SHX__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SHX $%2x%2x", MOS6502_SHX__242X2X_x_address_hi, MOS6502_SHX__242X2X_x_address_lo);

}
static void disasm_SAX__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SAX ($%2x, X)", MOS6502_SAX__LP__242X__X_RP__x_address_lo);

}
static void disasm_SAX__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SAX $%2x%2x", MOS6502_SAX__242X2X_x_address_hi, MOS6502_SAX__242X2X_x_address_lo);

}
static void disasm_SAX__242X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SAX $%2x, Y", MOS6502_SAX__242X__Y_x_address_lo);

}
static void disasm_SAX__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SAX $%2x", MOS6502_SAX__242X_x_address_lo);

}
static void disasm_LAX__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAX ($%2x), Y", MOS6502_LAX__LP__242X_RP___Y_x_lo_address);

}
static void disasm_LAX__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAX ($%2x, X)", MOS6502_LAX__LP__242X__X_RP__x_lo_address);

}
static void disasm_LAX__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAX $%2x%2x, Y", MOS6502_LAX__242X2X__Y_x_hi_address, MOS6502_LAX__242X2X__Y_x_lo_address);

}
static void disasm_LAX__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAX $%2x%2x", MOS6502_LAX__242X2X_x_hi_address, MOS6502_LAX__242X2X_x_lo_address);

}
static void disasm_LAX__242X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAX $%2x, Y", MOS6502_LAX__242X__Y_x_lo_address);

}
static void disasm_LAX__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LAX $%2x", MOS6502_LAX__242X_x_lo_address);

}
static void disasm_SBX__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBX #%2x", MOS6502_SBX__I2X_x_value);

}
static void disasm_ARR__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ARR #%2x", MOS6502_ARR__I2X_x_value);

}
static void disasm_ANC2__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ANC2 #%2x", MOS6502_ANC2__I2X_x_value);

}
static void disasm_ANC__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ANC #%2x", MOS6502_ANC__I2X_x_value);

}
static void disasm_ALR__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ALR #%2x", MOS6502_ALR__I2X_x_value);

}
static void disasm_NOP_5(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "NOP");

}
static void disasm_BIT__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BIT $%2x", MOS6502_BIT__242X_x_address_lo);

}
static void disasm_BIT__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BIT $%2x%2x", MOS6502_BIT__242X2X_x_address_hi, MOS6502_BIT__242X2X_x_address_lo);

}
static void disasm_RTS(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "RTS");

}
static void disasm_JSR__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JSR $%2x%2x", MOS6502_JSR__242X2X_x_address_hi, MOS6502_JSR__242X2X_x_address_lo);

}
static void disasm_JMP__LP__242X2X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JMP ($%2x%2x)", MOS6502_JMP__LP__242X2X_RP__x_address_hi, MOS6502_JMP__LP__242X2X_RP__x_address_lo);

}
static void disasm_JMP__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "JMP $%2x%2x", MOS6502_JMP__242X2X_x_address_hi, MOS6502_JMP__242X2X_x_address_lo);

}
static void disasm_BVS__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BVS #%2x", MOS6502_BVS__I2X_x_offset);

}
static void disasm_BVC__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BVC #%2x", MOS6502_BVC__I2X_x_offset);

}
static void disasm_BPL__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BPL #%2x", MOS6502_BPL__I2X_x_offset);

}
static void disasm_BNE__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BNE #%2x", MOS6502_BNE__I2X_x_offset);

}
static void disasm_BMI__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BMI #%2x", MOS6502_BMI__I2X_x_offset);

}
static void disasm_BEQ__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BEQ #%2x", MOS6502_BEQ__I2X_x_offset);

}
static void disasm_BCS__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BCS #%2x", MOS6502_BCS__I2X_x_offset);

}
static void disasm_BCC__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "BCC #%2x", MOS6502_BCC__I2X_x_offset);

}
static void disasm_ROR__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROR $%2x%2x, X", MOS6502_ROR__242X2X__X_x_address_hi, MOS6502_ROR__242X2X__X_x_address_lo);

}
static void disasm_ROR__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROR $%2x%2x", MOS6502_ROR__242X2X_x_address_hi, MOS6502_ROR__242X2X_x_address_lo);

}
static void disasm_ROR__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROR $%2x, X", MOS6502_ROR__242X__X_x_address_lo);

}
static void disasm_ROR__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROR $%2x", MOS6502_ROR__242X_x_address_lo);

}
static void disasm_ROR_A(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROR A");

}
static void disasm_ROL__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROL $%2x%2x", MOS6502_ROL__242X2X_x_address_hi, MOS6502_ROL__242X2X_x_address_lo);

}
static void disasm_ROL__242X2X_0(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROL $%2x%2x", MOS6502_ROL__242X2X_0_x_address_hi, MOS6502_ROL__242X2X_0_x_address_lo);

}
static void disasm_ROL_2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROL %2x, X", MOS6502_ROL_2X__X_x_address_lo);

}
static void disasm_ROL__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROL $%2x", MOS6502_ROL__242X_x_address_lo);

}
static void disasm_ROL_A(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ROL A");

}
static void disasm_LSR__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LSR $%2x%2x, X", MOS6502_LSR__242X2X__X_x_address_hi, MOS6502_LSR__242X2X__X_x_address_lo);

}
static void disasm_LSR__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LSR $%2x%2x", MOS6502_LSR__242X2X_x_address_hi, MOS6502_LSR__242X2X_x_address_lo);

}
static void disasm_LSR__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LSR $%2x, X", MOS6502_LSR__242X__X_x_address_lo);

}
static void disasm_LSR__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LSR $%2x", MOS6502_LSR__242X_x_address_lo);

}
static void disasm_LSR_A(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LSR A");

}
static void disasm_ASL__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ASL $%2x%2x, X", MOS6502_ASL__242X2X__X_x_address_hi, MOS6502_ASL__242X2X__X_x_address_lo);

}
static void disasm_ASL__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ASL $%2x%2x", MOS6502_ASL__242X2X_x_address_hi, MOS6502_ASL__242X2X_x_address_lo);

}
static void disasm_ASL__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ASL $%2x, X", MOS6502_ASL__242X__X_x_address_lo);

}
static void disasm_ASL__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ASL $%2x", MOS6502_ASL__242X_x_address_lo);

}
static void disasm_ASL_A(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ASL A");

}
static void disasm_CPY__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPY $%2x%2x", MOS6502_CPY__242X2X_x_address_hi, MOS6502_CPY__242X2X_x_address_lo);

}
static void disasm_CPY__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPY $%2x", MOS6502_CPY__242X_x_address_lo);

}
static void disasm_CPY__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPY #%2x", MOS6502_CPY__I2X_x_value);

}
static void disasm_CPX__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPX $%2x%2x", MOS6502_CPX__242X2X_x_address_hi, MOS6502_CPX__242X2X_x_address_lo);

}
static void disasm_CPX__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPX $%2x", MOS6502_CPX__242X_x_address_lo);

}
static void disasm_CPX__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CPX #%2x", MOS6502_CPX__I2X_x_value);

}
static void disasm_CMP__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP ($%2x), Y", MOS6502_CMP__LP__242X_RP___Y_x_address_lo);

}
static void disasm_CMP__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP ($%2x, X)", MOS6502_CMP__LP__242X__X_RP__x_address_lo);

}
static void disasm_CMP__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP $%2x%2x, Y", MOS6502_CMP__242X2X__Y_x_address_hi, MOS6502_CMP__242X2X__Y_x_address_lo);

}
static void disasm_CMP__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP $%2x%2x, X", MOS6502_CMP__242X2X__X_x_address_hi, MOS6502_CMP__242X2X__X_x_address_lo);

}
static void disasm_CMP__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP $%2x%2x", MOS6502_CMP__242X2X_x_address_hi, MOS6502_CMP__242X2X_x_address_lo);

}
static void disasm_CMP__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP $%2x, X", MOS6502_CMP__242X__X_x_address_lo);

}
static void disasm_CMP__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP $%2x", MOS6502_CMP__242X_x_address_lo);

}
static void disasm_CMP__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CMP #%2x", MOS6502_CMP__I2X_x_value);

}
static void disasm_SBC__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC ($%2x), Y", MOS6502_SBC__LP__242X_RP___Y_x_address_lo);

}
static void disasm_SBC__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC ($%2x, X)", MOS6502_SBC__LP__242X__X_RP__x_address_lo);

}
static void disasm_SBC__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC $%2x%2x, Y", MOS6502_SBC__242X2X__Y_x_address_hi, MOS6502_SBC__242X2X__Y_x_address_lo);

}
static void disasm_SBC__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC $%2x%2x, X", MOS6502_SBC__242X2X__X_x_address_hi, MOS6502_SBC__242X2X__X_x_address_lo);

}
static void disasm_SBC__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC $%2x%2x", MOS6502_SBC__242X2X_x_address_hi, MOS6502_SBC__242X2X_x_address_lo);

}
static void disasm_SBC__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC $%2x, X", MOS6502_SBC__242X__X_x_address_lo);

}
static void disasm_SBC__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC $%2x", MOS6502_SBC__242X_x_address_lo);

}
static void disasm_SBC__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SBC #%2x", MOS6502_SBC__I2X_x_value);

}
static void disasm_ADC__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC ($%2x), Y", MOS6502_ADC__LP__242X_RP___Y_x_address_lo);

}
static void disasm_ADC__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC ($%2x, X)", MOS6502_ADC__LP__242X__X_RP__x_address_lo);

}
static void disasm_ADC__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC $%2x%2x, Y", MOS6502_ADC__242X2X__Y_x_address_hi, MOS6502_ADC__242X2X__Y_x_address_lo);

}
static void disasm_ADC__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC $%2x%2x, X", MOS6502_ADC__242X2X__X_x_address_hi, MOS6502_ADC__242X2X__X_x_address_lo);

}
static void disasm_ADC__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC $%2x%2x", MOS6502_ADC__242X2X_x_address_hi, MOS6502_ADC__242X2X_x_address_lo);

}
static void disasm_ADC__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC $%2x, X", MOS6502_ADC__242X__X_x_lo_address);

}
static void disasm_ADC__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC $%2x", MOS6502_ADC__242X_x_lo_address);

}
static void disasm_ADC__ID(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ADC #%d", MOS6502_ADC__ID_x_value);

}
static void disasm_DEC__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEC $%2x%2x, X", MOS6502_DEC__242X2X__X_x_address_hi, MOS6502_DEC__242X2X__X_x_address_lo);

}
static void disasm_DEC__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEC $%2x%2x", MOS6502_DEC__242X2X_x_address_hi, MOS6502_DEC__242X2X_x_address_lo);

}
static void disasm_DEC__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEC $%2x, X", MOS6502_DEC__242X__X_x_address_lo);

}
static void disasm_DEC__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEC $%2x", MOS6502_DEC__242X_x_address_lo);

}
static void disasm_INC__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "INC $%2x%2x, X", MOS6502_INC__242X2X__X_x_address_hi, MOS6502_INC__242X2X__X_x_address_lo);

}
static void disasm_INC__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "INC $%2x%2x", MOS6502_INC__242X2X_x_address_hi, MOS6502_INC__242X2X_x_address_lo);

}
static void disasm_INC__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "INC $%2x, X", MOS6502_INC__242X__X_x_address_lo);

}
static void disasm_INC__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "INC $%2x", MOS6502_INC__242X_x_address_lo);

}
static void disasm_DEY(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEY");

}
static void disasm_INY(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "INY");

}
static void disasm_DEX(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "DEX");

}
static void disasm_INX(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "INX");

}
static void disasm_EOR__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR ($%2x), Y", MOS6502_EOR__LP__242X_RP___Y_x_address_lo);

}
static void disasm_EOR__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR ($%2x, X)", MOS6502_EOR__LP__242X__X_RP__x_address_lo);

}
static void disasm_EOR__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR $%2x%2x, Y", MOS6502_EOR__242X2X__Y_x_address_hi, MOS6502_EOR__242X2X__Y_x_address_lo);

}
static void disasm_EOR__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR $%2x%2x, X", MOS6502_EOR__242X2X__X_x_address_hi, MOS6502_EOR__242X2X__X_x_address_lo);

}
static void disasm_EOR__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR $%2x%2x", MOS6502_EOR__242X2X_x_address_hi, MOS6502_EOR__242X2X_x_address_lo);

}
static void disasm_EOR__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR $%2x, X", MOS6502_EOR__242X__X_x_address_lo);

}
static void disasm_EOR__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR $%2x", MOS6502_EOR__242X_x_address_lo);

}
static void disasm_EOR__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "EOR #%2x", MOS6502_EOR__I2X_x_value);

}
static void disasm_ORA__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA ($%2x), Y", MOS6502_ORA__LP__242X_RP___Y_x_address_lo);

}
static void disasm_ORA__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA ($%2x, X)", MOS6502_ORA__LP__242X__X_RP__x_address_lo);

}
static void disasm_ORA__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA $%2x%2x, Y", MOS6502_ORA__242X2X__Y_x_address_hi, MOS6502_ORA__242X2X__Y_x_address_lo);

}
static void disasm_ORA__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA $%2x%2x, X", MOS6502_ORA__242X2X__X_x_address_hi, MOS6502_ORA__242X2X__X_x_address_lo);

}
static void disasm_ORA__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA $%2x%2x", MOS6502_ORA__242X2X_x_address_hi, MOS6502_ORA__242X2X_x_address_lo);

}
static void disasm_ORA__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA $%2x, X", MOS6502_ORA__242X__X_x_address_lo);

}
static void disasm_ORA__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA $%2x", MOS6502_ORA__242X_x_address_lo);

}
static void disasm_ORA__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "ORA #%2x", MOS6502_ORA__I2X_x_value);

}
static void disasm_AND__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND ($%2x), Y", MOS6502_AND__LP__242X_RP___Y_x_address_lo);

}
static void disasm_AND__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND ($%2x, X)", MOS6502_AND__LP__242X__X_RP__x_address_lo);

}
static void disasm_AND__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND $%2x%2x, Y", MOS6502_AND__242X2X__Y_x_address_hi, MOS6502_AND__242X2X__Y_x_address_lo);

}
static void disasm_AND__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND $%2x%2x, X", MOS6502_AND__242X2X__X_x_address_hi, MOS6502_AND__242X2X__X_x_address_lo);

}
static void disasm_AND__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND $%2x%2x", MOS6502_AND__242X2X_x_address_hi, MOS6502_AND__242X2X_x_address_lo);

}
static void disasm_AND__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND $%2x, X", MOS6502_AND__242X__X_x_address_lo);

}
static void disasm_AND__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND $%2x", MOS6502_AND__242X_x_address_lo);

}
static void disasm_AND__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "AND #%2x", MOS6502_AND__I2X_x_value);

}
static void disasm_SEI(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEI");

}
static void disasm_SEC(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SEC");

}
static void disasm_SED(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "SED");

}
static void disasm_CLV(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLV");

}
static void disasm_CLI(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLI");

}
static void disasm_CLD(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLD");

}
static void disasm_CLC(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "CLC");

}
static void disasm_PLP(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "PLP");

}
static void disasm_PHP(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "PHP");

}
static void disasm_PLA(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "PLA");

}
static void disasm_PHA(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "PHA");

}
static void disasm_TYA(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "TYA");

}
static void disasm_TXS(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "TXS");

}
static void disasm_TXA(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "TXA");

}
static void disasm_TSX(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "TSX");

}
static void disasm_TAY(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "TAY");

}
static void disasm_TAX(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "TAX");

}
static void disasm_STY__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STY $%2x%2x", MOS6502_STY__242X2X_x_address_hi, MOS6502_STY__242X2X_x_address_lo);

}
static void disasm_STY__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STY $%2x, X", MOS6502_STY__242X__X_x_address_lo);

}
static void disasm_STY__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STY $%2x", MOS6502_STY__242X_x_address_lo);

}
static void disasm_STX__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STX $%2x%2x", MOS6502_STX__242X2X_x_address_hi, MOS6502_STX__242X2X_x_address_lo);

}
static void disasm_STX__242X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STX $%2x, Y", MOS6502_STX__242X__Y_x_address_lo);

}
static void disasm_STX__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STX $%2x", MOS6502_STX__242X_x_address_lo);

}
static void disasm_STA__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA ($%2x, X)", MOS6502_STA__LP__242X__X_RP__x_address_lo);

}
static void disasm_STA__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA ($%2x), Y", MOS6502_STA__LP__242X_RP___Y_x_address_lo);

}
static void disasm_STA__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA $%2x%2x, Y", MOS6502_STA__242X2X__Y_x_address_hi, MOS6502_STA__242X2X__Y_x_address_lo);

}
static void disasm_STA__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA $%2x%2x, X", MOS6502_STA__242X2X__X_x_address_hi, MOS6502_STA__242X2X__X_x_address_lo);

}
static void disasm_STA__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA $%2x%2x", MOS6502_STA__242X2X_x_address_hi, MOS6502_STA__242X2X_x_address_lo);

}
static void disasm_STA__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA $%2x, X", MOS6502_STA__242X__X_x_address_lo);

}
static void disasm_STA__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "STA $%2x", MOS6502_STA__242X_x_address_lo);

}
static void disasm_LDY__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDY $%2x%2x, X", MOS6502_LDY__242X2X__X_x_address_hi, MOS6502_LDY__242X2X__X_x_address_lo);

}
static void disasm_LDY__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDY $%2x%2x", MOS6502_LDY__242X2X_x_address_hi, MOS6502_LDY__242X2X_x_address_lo);

}
static void disasm_LDY__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDY $%2x, X", MOS6502_LDY__242X__X_x_address_lo);

}
static void disasm_LDY__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDY $%2x", MOS6502_LDY__242X_x_address_lo);

}
static void disasm_LDY__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDY #%2x", MOS6502_LDY__I2X_x_value);

}
static void disasm_LDX__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDX $%2x%2x, Y", MOS6502_LDX__242X2X__Y_x_address_hi, MOS6502_LDX__242X2X__Y_x_address_lo);

}
static void disasm_LDX__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDX $%2x%2x", MOS6502_LDX__242X2X_x_address_hi, MOS6502_LDX__242X2X_x_address_lo);

}
static void disasm_LDX__242X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDX $%2x, Y", MOS6502_LDX__242X__Y_x_address_lo);

}
static void disasm_LDX__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDX $%2x", MOS6502_LDX__242X_x_address_lo);

}
static void disasm_LDX__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDX #%2x", MOS6502_LDX__I2X_x_value);

}
static void disasm_LDA__LP__242X_RP___Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA ($%2x), Y", MOS6502_LDA__LP__242X_RP___Y_x_address_lo);

}
static void disasm_LDA__LP__242X__X_RP_(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA ($%2x, X)", MOS6502_LDA__LP__242X__X_RP__x_address_lo);

}
static void disasm_LDA__242X2X__Y(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA $%2x%2x, Y", MOS6502_LDA__242X2X__Y_x_address_hi, MOS6502_LDA__242X2X__Y_x_address_lo);

}
static void disasm_LDA__242X2X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA $%2x%2x, X", MOS6502_LDA__242X2X__X_x_address_hi, MOS6502_LDA__242X2X__X_x_address_lo);

}
static void disasm_LDA__242X2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA $%2x%2x", MOS6502_LDA__242X2X_x_address_hi, MOS6502_LDA__242X2X_x_address_lo);

}
static void disasm_LDA__242X__X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA $%2x, X", MOS6502_LDA__242X__X_x_address_lo);

}
static void disasm_LDA__242X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA $%2x", MOS6502_LDA__242X_x_address_lo);

}
static void disasm_LDA__I2X(char *__buffer, mos6502_inst_t *inst) {
		__buffer += sprintf(__buffer, "LDA #%2x", MOS6502_LDA__I2X_x_value);

}


/* table */
static disasm_t disasm_tab[] = {
	disasm_unknown,
	disasm_JAM,
	disasm_JAM_0,
	disasm_JAM_1,
	disasm_JAM_2,
	disasm_JAM_3,
	disasm_JAM_4,
	disasm_JAM_5,
	disasm_JAM_6,
	disasm_JAM_7,
	disasm_JAM_8,
	disasm_JAM_9,
	disasm_JAM_10,
	disasm_IGN__242X__X,
	disasm_IGN__242X__X_0,
	disasm_IGN__242X__X_1,
	disasm_IGN__242X__X_2,
	disasm_IGN__242X__X_3,
	disasm_IGN__242X__X_4,
	disasm_IGN__242X,
	disasm_IGN__242X_0,
	disasm_IGN__242X_1,
	disasm_IGN__242X2X__X,
	disasm_IGN__242X2X__X_0,
	disasm_IGN__242X2X__X_1,
	disasm_IGN__242X2X__X_2,
	disasm_IGN__242X2X__X_3,
	disasm_IGN__242X2X__X_4,
	disasm_IGN__242X2X,
	disasm_SKB__I2X,
	disasm_SKB__I2X_0,
	disasm_SKB__I2X_1,
	disasm_SKB__I2X_2,
	disasm_SKB__I2X_3,
	disasm_NOP,
	disasm_NOP_0,
	disasm_NOP_1,
	disasm_NOP_2,
	disasm_NOP_3,
	disasm_NOP_4,
	disasm_USBC__I2X,
	disasm_SLO__LP__242X_RP___Y,
	disasm_SLO__LP__242X__X_RP_,
	disasm_SLO__242X2X__Y,
	disasm_SLO__242X2X__X,
	disasm_SLO__242X2X,
	disasm_SLO__242X__X,
	disasm_SLO__242X,
	disasm_RLA__LP__242X_RP___Y,
	disasm_RLA__LP__242X__X_RP_,
	disasm_RLA__242X2X__Y,
	disasm_RLA__242X2X__X,
	disasm_RLA__242X2X,
	disasm_RLA__242X__X,
	disasm_RLA__242X,
	disasm_RRA__LP__242X_RP__Y,
	disasm_RRA__LP__242X_X_RP_,
	disasm_RRA__242X2X__Y,
	disasm_RRA__242X2X__X,
	disasm_RRA__242X2X,
	disasm_RRA__242X__X,
	disasm_RRA__242X,
	disasm_SRE__LP__242X_RP___Y,
	disasm_SRE__LP__242X__X_RP_,
	disasm_SRE__242X2X__Y,
	disasm_SRE__242X2X__X,
	disasm_SRE__242X2X,
	disasm_SRE__242X__X,
	disasm_SRE__242X,
	disasm_ISC__LP__242X_RP___Y,
	disasm_ISC__LP__242X__X_RP_,
	disasm_ISC__242X2X__Y,
	disasm_ISC__242X2X__X,
	disasm_ISC__242X2X,
	disasm_ISC__242X__X,
	disasm_ISC__242X,
	disasm_DCP__LP__242X_RP___Y,
	disasm_DCP__LP__242X__X_RP_,
	disasm_DCP__242X2X__Y,
	disasm_DCP__242X2X__X,
	disasm_DCP__242X2X,
	disasm_DCP__242X__X,
	disasm_DCP__242X,
	disasm_SHA__LP__242X_RP___Y,
	disasm_SHA__242X2X,
	disasm_SHY__242X2X,
	disasm_SHX__242X2X,
	disasm_SAX__LP__242X__X_RP_,
	disasm_SAX__242X2X,
	disasm_SAX__242X__Y,
	disasm_SAX__242X,
	disasm_LAX__LP__242X_RP___Y,
	disasm_LAX__LP__242X__X_RP_,
	disasm_LAX__242X2X__Y,
	disasm_LAX__242X2X,
	disasm_LAX__242X__Y,
	disasm_LAX__242X,
	disasm_SBX__I2X,
	disasm_ARR__I2X,
	disasm_ANC2__I2X,
	disasm_ANC__I2X,
	disasm_ALR__I2X,
	disasm_NOP_5,
	disasm_BIT__242X,
	disasm_BIT__242X2X,
	disasm_RTS,
	disasm_JSR__242X2X,
	disasm_JMP__LP__242X2X_RP_,
	disasm_JMP__242X2X,
	disasm_BVS__I2X,
	disasm_BVC__I2X,
	disasm_BPL__I2X,
	disasm_BNE__I2X,
	disasm_BMI__I2X,
	disasm_BEQ__I2X,
	disasm_BCS__I2X,
	disasm_BCC__I2X,
	disasm_ROR__242X2X__X,
	disasm_ROR__242X2X,
	disasm_ROR__242X__X,
	disasm_ROR__242X,
	disasm_ROR_A,
	disasm_ROL__242X2X,
	disasm_ROL__242X2X_0,
	disasm_ROL_2X__X,
	disasm_ROL__242X,
	disasm_ROL_A,
	disasm_LSR__242X2X__X,
	disasm_LSR__242X2X,
	disasm_LSR__242X__X,
	disasm_LSR__242X,
	disasm_LSR_A,
	disasm_ASL__242X2X__X,
	disasm_ASL__242X2X,
	disasm_ASL__242X__X,
	disasm_ASL__242X,
	disasm_ASL_A,
	disasm_CPY__242X2X,
	disasm_CPY__242X,
	disasm_CPY__I2X,
	disasm_CPX__242X2X,
	disasm_CPX__242X,
	disasm_CPX__I2X,
	disasm_CMP__LP__242X_RP___Y,
	disasm_CMP__LP__242X__X_RP_,
	disasm_CMP__242X2X__Y,
	disasm_CMP__242X2X__X,
	disasm_CMP__242X2X,
	disasm_CMP__242X__X,
	disasm_CMP__242X,
	disasm_CMP__I2X,
	disasm_SBC__LP__242X_RP___Y,
	disasm_SBC__LP__242X__X_RP_,
	disasm_SBC__242X2X__Y,
	disasm_SBC__242X2X__X,
	disasm_SBC__242X2X,
	disasm_SBC__242X__X,
	disasm_SBC__242X,
	disasm_SBC__I2X,
	disasm_ADC__LP__242X_RP___Y,
	disasm_ADC__LP__242X__X_RP_,
	disasm_ADC__242X2X__Y,
	disasm_ADC__242X2X__X,
	disasm_ADC__242X2X,
	disasm_ADC__242X__X,
	disasm_ADC__242X,
	disasm_ADC__ID,
	disasm_DEC__242X2X__X,
	disasm_DEC__242X2X,
	disasm_DEC__242X__X,
	disasm_DEC__242X,
	disasm_INC__242X2X__X,
	disasm_INC__242X2X,
	disasm_INC__242X__X,
	disasm_INC__242X,
	disasm_DEY,
	disasm_INY,
	disasm_DEX,
	disasm_INX,
	disasm_EOR__LP__242X_RP___Y,
	disasm_EOR__LP__242X__X_RP_,
	disasm_EOR__242X2X__Y,
	disasm_EOR__242X2X__X,
	disasm_EOR__242X2X,
	disasm_EOR__242X__X,
	disasm_EOR__242X,
	disasm_EOR__I2X,
	disasm_ORA__LP__242X_RP___Y,
	disasm_ORA__LP__242X__X_RP_,
	disasm_ORA__242X2X__Y,
	disasm_ORA__242X2X__X,
	disasm_ORA__242X2X,
	disasm_ORA__242X__X,
	disasm_ORA__242X,
	disasm_ORA__I2X,
	disasm_AND__LP__242X_RP___Y,
	disasm_AND__LP__242X__X_RP_,
	disasm_AND__242X2X__Y,
	disasm_AND__242X2X__X,
	disasm_AND__242X2X,
	disasm_AND__242X__X,
	disasm_AND__242X,
	disasm_AND__I2X,
	disasm_SEI,
	disasm_SEC,
	disasm_SED,
	disasm_CLV,
	disasm_CLI,
	disasm_CLD,
	disasm_CLC,
	disasm_PLP,
	disasm_PHP,
	disasm_PLA,
	disasm_PHA,
	disasm_TYA,
	disasm_TXS,
	disasm_TXA,
	disasm_TSX,
	disasm_TAY,
	disasm_TAX,
	disasm_STY__242X2X,
	disasm_STY__242X__X,
	disasm_STY__242X,
	disasm_STX__242X2X,
	disasm_STX__242X__Y,
	disasm_STX__242X,
	disasm_STA__LP__242X__X_RP_,
	disasm_STA__LP__242X_RP___Y,
	disasm_STA__242X2X__Y,
	disasm_STA__242X2X__X,
	disasm_STA__242X2X,
	disasm_STA__242X__X,
	disasm_STA__242X,
	disasm_LDY__242X2X__X,
	disasm_LDY__242X2X,
	disasm_LDY__242X__X,
	disasm_LDY__242X,
	disasm_LDY__I2X,
	disasm_LDX__242X2X__Y,
	disasm_LDX__242X2X,
	disasm_LDX__242X__Y,
	disasm_LDX__242X,
	disasm_LDX__I2X,
	disasm_LDA__LP__242X_RP___Y,
	disasm_LDA__LP__242X__X_RP_,
	disasm_LDA__242X2X__Y,
	disasm_LDA__242X2X__X,
	disasm_LDA__242X2X,
	disasm_LDA__242X__X,
	disasm_LDA__242X,
	disasm_LDA__I2X
};

/**
 * Disassemble the given instruction.
 * @param buffer	Buffer to write in.
 * @param inst		Decode instruction.
 */
void mos6502_disasm(char *buffer, mos6502_inst_t *inst) {
	disasm_tab[inst->ident](buffer, inst);
}
