/* Generated by gep (125/04/14 21:47:43) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_AVR_INCLUDE_AVR_FETCH_TABLE_H
#define GLISS_AVR_INCLUDE_AVR_FETCH_TABLE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include <avr/id.h>
#include <avr/gen_int.h>

#include <avr/mem.h>
#include <avr/grt.h>
#include <avr/error.h>
#include <avr/gen_int.h>
#include <avr/env.h>
#include <avr/loader.h>
#include <avr/code.h>


/* data structures */

typedef enum
{
   INSTRUCTION,
   TABLEFETCH
} Type_Decode;

typedef struct
{
	Type_Decode type;
	void *ptr;	/* will be used to store an instruction ID or the address of a Table_Decodage */
} Decode_Ent;

/* CISC single instruction set */
typedef struct Table_Decodage_CISC {
        mask_t        *mask;
        Decode_Ent      *table;
} Table_Decodage_CISC;

static Decode_Ent table_table_111_1_11[4] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_SBRC_RD__D}	/* SBRC_RD__D, 16 bits, mask=1111111000001000, val=1111110XXXXX0XXX */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_SBRS_RD__D}	/* SBRS_RD__D, 16 bits, mask=1111111000001000, val=1111111XXXXX0XXX */,
	{INSTRUCTION, (void *)AVR_UNKNOWN}
};
static uint32_t tab_mask_111_1_11[1] = {0X2080000};
static mask_t mask_111_1_11 = {
	tab_mask_111_1_11,	16};
static Table_Decodage_CISC _table_111_1_11 = {&mask_111_1_11, table_table_111_1_11};
Table_Decodage_CISC *avr_table_111_1_11 = &_table_111_1_11;

static Decode_Ent table_table_111_1_10[4] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_BLD_RD__D}	/* BLD_RD__D, 16 bits, mask=1111111000001000, val=1111100XXXXX0XXX */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_BST_RD__D}	/* BST_RD__D, 16 bits, mask=1111111000001000, val=1111101XXXXX0XXX */,
	{INSTRUCTION, (void *)AVR_UNKNOWN}
};
static uint32_t tab_mask_111_1_10[1] = {0X2080000};
static mask_t mask_111_1_10 = {
	tab_mask_111_1_10,	16};
static Table_Decodage_CISC _table_111_1_10 = {&mask_111_1_10, table_table_111_1_10};
Table_Decodage_CISC *avr_table_111_1_10 = &_table_111_1_10;

static Decode_Ent table_table_111_1_01[8] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_BRCC___P_D__3B__P_04X}	/* BRCC___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX000 */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_BRNE___P_D__3B__P_04X}	/* BRNE___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX001 */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_BRPL___P_D__3B__P_04X}	/* BRPL___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX010 */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_BRVC___P_D__3B__P_04X}	/* BRVC___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX011 */,
	/* 0X4,4 */	{INSTRUCTION, (void *)AVR_BRGE___P_D__3B__P_04X}	/* BRGE___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX100 */,
	/* 0X5,5 */	{INSTRUCTION, (void *)AVR_BRHC___P_D__3B__P_04X}	/* BRHC___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX101 */,
	/* 0X6,6 */	{INSTRUCTION, (void *)AVR_BRTC___P_D__3B__P_04X}	/* BRTC___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX110 */,
	/* 0X7,7 */	{INSTRUCTION, (void *)AVR_BRID___P_D__3B__P_04X}	/* BRID___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111101XXXXXXX111 */
};
static uint32_t tab_mask_111_1_01[1] = {0X70000};
static mask_t mask_111_1_01 = {
	tab_mask_111_1_01,	16};
static Table_Decodage_CISC _table_111_1_01 = {&mask_111_1_01, table_table_111_1_01};
Table_Decodage_CISC *avr_table_111_1_01 = &_table_111_1_01;

static Decode_Ent table_table_111_1_00[8] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_BRCS___P_D__3B__P_04X}	/* BRCS___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX000 */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_BREQ___P_D__3B__P_04X}	/* BREQ___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX001 */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_BRMI___P_D__3B__P_04X}	/* BRMI___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX010 */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_BRVS___P_D__3B__P_04X}	/* BRVS___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX011 */,
	/* 0X4,4 */	{INSTRUCTION, (void *)AVR_BRLT___P_D__3B__P_04X}	/* BRLT___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX100 */,
	/* 0X5,5 */	{INSTRUCTION, (void *)AVR_BRHS___P_D__3B__P_04X}	/* BRHS___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX101 */,
	/* 0X6,6 */	{INSTRUCTION, (void *)AVR_BRTS___P_D__3B__P_04X}	/* BRTS___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX110 */,
	/* 0X7,7 */	{INSTRUCTION, (void *)AVR_BRIE___P_D__3B__P_04X}	/* BRIE___P_D__3B__P_04X, 16 bits, mask=1111110000000111, val=111100XXXXXXX111 */
};
static uint32_t tab_mask_111_1_00[1] = {0X70000};
static mask_t mask_111_1_00 = {
	tab_mask_111_1_00,	16};
static Table_Decodage_CISC _table_111_1_00 = {&mask_111_1_00, table_table_111_1_00};
Table_Decodage_CISC *avr_table_111_1_00 = &_table_111_1_00;

static Decode_Ent table_table_111_1[4] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_111_1_00},
	/* 0X1,1 */	{TABLEFETCH, &_table_111_1_01},
	/* 0X2,2 */	{TABLEFETCH, &_table_111_1_10},
	/* 0X3,3 */	{TABLEFETCH, &_table_111_1_11}
};
static uint32_t tab_mask_111_1[1] = {0XC000000};
static mask_t mask_111_1 = {
	tab_mask_111_1,	16};
static Table_Decodage_CISC _table_111_1 = {&mask_111_1, table_table_111_1};
Table_Decodage_CISC *avr_table_111_1 = &_table_111_1;

static Decode_Ent table_table_111[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_RCALL_D__LP_04X_RP_}	/* RCALL_D__LP_04X_RP_, 16 bits, mask=1111000000000000, val=1101XXXXXXXXXXXX */,
	/* 0X1,1 */	{TABLEFETCH, &_table_111_1}
};
static uint32_t tab_mask_111[1] = {0X20000000};
static mask_t mask_111 = {
	tab_mask_111,	16};
static Table_Decodage_CISC _table_111 = {&mask_111, table_table_111};
Table_Decodage_CISC *avr_table_111 = &_table_111;

static Decode_Ent table_table_110[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_RJMP___P_D__3B_04X}	/* RJMP___P_D__3B_04X, 16 bits, mask=1111000000000000, val=1100XXXXXXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_LDI_RD__D}	/* LDI_RD__D, 16 bits, mask=1111000000000000, val=1110XXXXXXXXXXXX */
};
static uint32_t tab_mask_110[1] = {0X20000000};
static mask_t mask_110 = {
	tab_mask_110,	16};
static Table_Decodage_CISC _table_110 = {&mask_110, table_table_110};
Table_Decodage_CISC *avr_table_110 = &_table_110;

static Decode_Ent table_table_101_01_0[4] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_CBI_IOD__D}	/* CBI_IOD__D, 16 bits, mask=1111111100000000, val=10011000XXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_SBIC_IOD__D_0}	/* SBIC_IOD__D_0, 16 bits, mask=1111111100000000, val=10011001XXXXXXXX */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_SBI_IOD__D}	/* SBI_IOD__D, 16 bits, mask=1111111100000000, val=10011010XXXXXXXX */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_SBIC_IOD__D}	/* SBIC_IOD__D, 16 bits, mask=1111111100000000, val=10011011XXXXXXXX */
};
static uint32_t tab_mask_101_01_0[1] = {0X3000000};
static mask_t mask_101_01_0 = {
	tab_mask_101_01_0,	16};
static Table_Decodage_CISC _table_101_01_0 = {&mask_101_01_0, table_table_101_01_0};
Table_Decodage_CISC *avr_table_101_01_0 = &_table_101_01_0;

static Decode_Ent table_table_101_01[2] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_101_01_0},
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_MUL_RD__RD}	/* MUL_RD__RD, 16 bits, mask=1111110000000000, val=100111XXXXXXXXXX */
};
static uint32_t tab_mask_101_01[1] = {0X4000000};
static mask_t mask_101_01 = {
	tab_mask_101_01,	16};
static Table_Decodage_CISC _table_101_01 = {&mask_101_01, table_table_101_01};
Table_Decodage_CISC *avr_table_101_01 = &_table_101_01;

static Decode_Ent table_table_101_00_11[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_ADIW_RD_3ARD__D}	/* ADIW_RD_3ARD__D, 16 bits, mask=1111111100000000, val=10010110XXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_SBIW_RD_3ARD__D}	/* SBIW_RD_3ARD__D, 16 bits, mask=1111111100000000, val=10010111XXXXXXXX */
};
static uint32_t tab_mask_101_00_11[1] = {0X1000000};
static mask_t mask_101_00_11 = {
	tab_mask_101_00_11,	16};
static Table_Decodage_CISC _table_101_00_11 = {&mask_101_00_11, table_table_101_00_11};
Table_Decodage_CISC *avr_table_101_00_11 = &_table_101_00_11;

static Decode_Ent table_table_101_00_10_100[64] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_SEC}	/* SEC, 16 bits, mask=1111111111111111, val=1001010000001000 */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_IJMP}	/* IJMP, 16 bits, mask=1111111111111111, val=1001010000001001 */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_SEZ}	/* SEZ, 16 bits, mask=1111111111111111, val=1001010000011000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X4,4 */	{INSTRUCTION, (void *)AVR_SEN}	/* SEN, 16 bits, mask=1111111111111111, val=1001010000101000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X6,6 */	{INSTRUCTION, (void *)AVR_SEV}	/* SEV, 16 bits, mask=1111111111111111, val=1001010000111000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X8,8 */	{INSTRUCTION, (void *)AVR_SES}	/* SES, 16 bits, mask=1111111111111111, val=1001010001001000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0XA,10 */	{INSTRUCTION, (void *)AVR_SEH}	/* SEH, 16 bits, mask=1111111111111111, val=1001010001011000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0XC,12 */	{INSTRUCTION, (void *)AVR_SET}	/* SET, 16 bits, mask=1111111111111111, val=1001010001101000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0XE,14 */	{INSTRUCTION, (void *)AVR_SEI}	/* SEI, 16 bits, mask=1111111111111111, val=1001010001111000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X10,16 */	{INSTRUCTION, (void *)AVR_CLC}	/* CLC, 16 bits, mask=1111111111111111, val=1001010010001000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X12,18 */	{INSTRUCTION, (void *)AVR_CLZ}	/* CLZ, 16 bits, mask=1111111111111111, val=1001010010011000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X14,20 */	{INSTRUCTION, (void *)AVR_CLN}	/* CLN, 16 bits, mask=1111111111111111, val=1001010010101000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X16,22 */	{INSTRUCTION, (void *)AVR_CLV}	/* CLV, 16 bits, mask=1111111111111111, val=1001010010111000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X18,24 */	{INSTRUCTION, (void *)AVR_CLS}	/* CLS, 16 bits, mask=1111111111111111, val=1001010011001000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X1A,26 */	{INSTRUCTION, (void *)AVR_CLH}	/* CLH, 16 bits, mask=1111111111111111, val=1001010011011000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X1C,28 */	{INSTRUCTION, (void *)AVR_CLT}	/* CLT, 16 bits, mask=1111111111111111, val=1001010011101000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X1E,30 */	{INSTRUCTION, (void *)AVR_CLI}	/* CLI, 16 bits, mask=1111111111111111, val=1001010011111000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X20,32 */	{INSTRUCTION, (void *)AVR_RET}	/* RET, 16 bits, mask=1111111111111111, val=1001010100001000 */,
	/* 0X21,33 */	{INSTRUCTION, (void *)AVR_ICALL}	/* ICALL, 16 bits, mask=1111111111111111, val=1001010100001001 */,
	/* 0X22,34 */	{INSTRUCTION, (void *)AVR_RETI}	/* RETI, 16 bits, mask=1111111111111111, val=1001010100011000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X38,56 */	{INSTRUCTION, (void *)AVR_LPM}	/* LPM, 16 bits, mask=1111111111111111, val=1001010111001000 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN}
};
static uint32_t tab_mask_101_00_10_100[1] = {0X1F10000};
static mask_t mask_101_00_10_100 = {
	tab_mask_101_00_10_100,	16};
static Table_Decodage_CISC _table_101_00_10_100 = {&mask_101_00_10_100, table_table_101_00_10_100};
Table_Decodage_CISC *avr_table_101_00_10_100 = &_table_101_00_10_100;

static Decode_Ent table_table_101_00_10_011[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_LSR_RD}	/* LSR_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0110 */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_ROR_RD}	/* ROR_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0111 */
};
static uint32_t tab_mask_101_00_10_011[1] = {0X10000};
static mask_t mask_101_00_10_011 = {
	tab_mask_101_00_10_011,	16};
static Table_Decodage_CISC _table_101_00_10_011 = {&mask_101_00_10_011, table_table_101_00_10_011};
Table_Decodage_CISC *avr_table_101_00_10_011 = &_table_101_00_10_011;

static Decode_Ent table_table_101_00_10_001[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_SWAP_RD}	/* SWAP_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0010 */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_INC_RD}	/* INC_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0011 */
};
static uint32_t tab_mask_101_00_10_001[1] = {0X10000};
static mask_t mask_101_00_10_001 = {
	tab_mask_101_00_10_001,	16};
static Table_Decodage_CISC _table_101_00_10_001 = {&mask_101_00_10_001, table_table_101_00_10_001};
Table_Decodage_CISC *avr_table_101_00_10_001 = &_table_101_00_10_001;

static Decode_Ent table_table_101_00_10_000[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_COM_RD}	/* COM_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0000 */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_NEG_RD}	/* NEG_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0001 */
};
static uint32_t tab_mask_101_00_10_000[1] = {0X10000};
static mask_t mask_101_00_10_000 = {
	tab_mask_101_00_10_000,	16};
static Table_Decodage_CISC _table_101_00_10_000 = {&mask_101_00_10_000, table_table_101_00_10_000};
Table_Decodage_CISC *avr_table_101_00_10_000 = &_table_101_00_10_000;

static Decode_Ent table_table_101_00_10[8] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_101_00_10_000},
	/* 0X1,1 */	{TABLEFETCH, &_table_101_00_10_001},
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_ASR_RD}	/* ASR_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX0101 */,
	/* 0X3,3 */	{TABLEFETCH, &_table_101_00_10_011},
	/* 0X4,4 */	{TABLEFETCH, &_table_101_00_10_100},
	/* 0X5,5 */	{INSTRUCTION, (void *)AVR_DEC_RD}	/* DEC_RD, 16 bits, mask=1111111000001111, val=1001010XXXXX1010 */,
	/* 0X6,6 */	{INSTRUCTION, (void *)AVR_JMP_D__LP_04X_RP_}	/* JMP_D__LP_04X_RP_, 32 bits, mask=11111110000011100000000000000000, val=1001010XXXXX110XXXXXXXXXXXXXXXXX */,
	/* 0X7,7 */	{INSTRUCTION, (void *)AVR_CALL_D__LP_04X_RP_}	/* CALL_D__LP_04X_RP_, 32 bits, mask=11111110000011100000000000000000, val=1001010XXXXX111XXXXXXXXXXXXXXXXX */
};
static uint32_t tab_mask_101_00_10[1] = {0XE0000};
static mask_t mask_101_00_10 = {
	tab_mask_101_00_10,	32};
static Table_Decodage_CISC _table_101_00_10 = {&mask_101_00_10, table_table_101_00_10};
Table_Decodage_CISC *avr_table_101_00_10 = &_table_101_00_10;

static Decode_Ent table_table_101_00_01[16] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_STS_D__RD}	/* STS_D__RD, 32 bits, mask=11111110000011110000000000000000, val=1001001XXXXX0000XXXXXXXXXXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_ST_Z_P___RD}	/* ST_Z_P___RD, 16 bits, mask=1111111000001111, val=1001001XXXXX0001 */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_ST__M_Z__RD}	/* ST__M_Z__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX0010 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X4,4 */	{INSTRUCTION, (void *)AVR_XCH_Z__RD}	/* XCH_Z__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX0100 */,
	/* 0X5,5 */	{INSTRUCTION, (void *)AVR_LAS_Z__RD}	/* LAS_Z__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX0101 */,
	/* 0X6,6 */	{INSTRUCTION, (void *)AVR_LAC_Z__RD}	/* LAC_Z__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX0110 */,
	/* 0X7,7 */	{INSTRUCTION, (void *)AVR_LAT_Z__RD}	/* LAT_Z__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX0111 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X9,9 */	{INSTRUCTION, (void *)AVR_ST_Y_P___RD}	/* ST_Y_P___RD, 16 bits, mask=1111111000001111, val=1001001XXXXX1001 */,
	/* 0XA,10 */	{INSTRUCTION, (void *)AVR_ST__M_Y__RD}	/* ST__M_Y__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX1010 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0XC,12 */	{INSTRUCTION, (void *)AVR_ST_X__RD}	/* ST_X__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX1100 */,
	/* 0XD,13 */	{INSTRUCTION, (void *)AVR_ST_X_P___RD}	/* ST_X_P___RD, 16 bits, mask=1111111000001111, val=1001001XXXXX1101 */,
	/* 0XE,14 */	{INSTRUCTION, (void *)AVR_ST__M_X__RD}	/* ST__M_X__RD, 16 bits, mask=1111111000001111, val=1001001XXXXX1110 */,
	/* 0XF,15 */	{INSTRUCTION, (void *)AVR_PUSH_RD}	/* PUSH_RD, 16 bits, mask=1111111000001111, val=1001001XXXXX1111 */
};
static uint32_t tab_mask_101_00_01[1] = {0XF0000};
static mask_t mask_101_00_01 = {
	tab_mask_101_00_01,	32};
static Table_Decodage_CISC _table_101_00_01 = {&mask_101_00_01, table_table_101_00_01};
Table_Decodage_CISC *avr_table_101_00_01 = &_table_101_00_01;

static Decode_Ent table_table_101_00_00[16] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_LDS_RD__0X04X}	/* LDS_RD__0X04X, 32 bits, mask=11111110000011110000000000000000, val=1001000XXXXX0000XXXXXXXXXXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_LD_RD__Z_P_}	/* LD_RD__Z_P_, 16 bits, mask=1111111000001111, val=1001000XXXXX0001 */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_LD_RD___M_Z}	/* LD_RD___M_Z, 16 bits, mask=1111111000001111, val=1001000XXXXX0010 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X4,4 */	{INSTRUCTION, (void *)AVR_LPM_RD__Z}	/* LPM_RD__Z, 16 bits, mask=1111111000001111, val=1001000XXXXX0100 */,
	/* 0X5,5 */	{INSTRUCTION, (void *)AVR_LPM_RD__Z_P_}	/* LPM_RD__Z_P_, 16 bits, mask=1111111000001111, val=1001000XXXXX0101 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X9,9 */	{INSTRUCTION, (void *)AVR_LD_RD__Y_P_}	/* LD_RD__Y_P_, 16 bits, mask=1111111000001111, val=1001000XXXXX1001 */,
	/* 0XA,10 */	{INSTRUCTION, (void *)AVR_LD_RD___M_Y}	/* LD_RD___M_Y, 16 bits, mask=1111111000001111, val=1001000XXXXX1010 */,
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0XC,12 */	{INSTRUCTION, (void *)AVR_LD_RD__X}	/* LD_RD__X, 16 bits, mask=1111111000001111, val=1001000XXXXX1100 */,
	/* 0XD,13 */	{INSTRUCTION, (void *)AVR_LD_RD__X_P_}	/* LD_RD__X_P_, 16 bits, mask=1111111000001111, val=1001000XXXXX1101 */,
	/* 0XE,14 */	{INSTRUCTION, (void *)AVR_LD_RD___M_X}	/* LD_RD___M_X, 16 bits, mask=1111111000001111, val=1001000XXXXX1110 */,
	/* 0XF,15 */	{INSTRUCTION, (void *)AVR_POP_RD}	/* POP_RD, 16 bits, mask=1111111000001111, val=1001000XXXXX1111 */
};
static uint32_t tab_mask_101_00_00[1] = {0XF0000};
static mask_t mask_101_00_00 = {
	tab_mask_101_00_00,	32};
static Table_Decodage_CISC _table_101_00_00 = {&mask_101_00_00, table_table_101_00_00};
Table_Decodage_CISC *avr_table_101_00_00 = &_table_101_00_00;

static Decode_Ent table_table_101_00[4] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_101_00_00},
	/* 0X1,1 */	{TABLEFETCH, &_table_101_00_01},
	/* 0X2,2 */	{TABLEFETCH, &_table_101_00_10},
	/* 0X3,3 */	{TABLEFETCH, &_table_101_00_11}
};
static uint32_t tab_mask_101_00[1] = {0X6000000};
static mask_t mask_101_00 = {
	tab_mask_101_00,	32};
static Table_Decodage_CISC _table_101_00 = {&mask_101_00, table_table_101_00};
Table_Decodage_CISC *avr_table_101_00 = &_table_101_00;

static Decode_Ent table_table_101[4] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_101_00},
	/* 0X1,1 */	{TABLEFETCH, &_table_101_01},
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_IN_RD__D}	/* IN_RD__D, 16 bits, mask=1111100000000000, val=10110XXXXXXXXXXX */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_OUT_D__RD}	/* OUT_D__RD, 16 bits, mask=1111100000000000, val=10111XXXXXXXXXXX */
};
static uint32_t tab_mask_101[1] = {0X28000000};
static mask_t mask_101 = {
	tab_mask_101,	32};
static Table_Decodage_CISC _table_101 = {&mask_101, table_table_101};
Table_Decodage_CISC *avr_table_101 = &_table_101;

static Decode_Ent table_table_100[4] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_LDD_RD__Z_P_D}	/* LDD_RD__Z_P_D, 16 bits, mask=1101001000001000, val=10X0XX0XXXXX0XXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_LDD_RD__Y_P_D}	/* LDD_RD__Y_P_D, 16 bits, mask=1101001000001000, val=10X0XX0XXXXX1XXX */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_STD_Z_P_D__RD}	/* STD_Z_P_D__RD, 16 bits, mask=1101001000001000, val=10X0XX1XXXXX0XXX */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_STD_Y_P_D__RD}	/* STD_Y_P_D__RD, 16 bits, mask=1101001000001000, val=10X0XX1XXXXX1XXX */
};
static uint32_t tab_mask_100[1] = {0X2080000};
static mask_t mask_100 = {
	tab_mask_100,	16};
static Table_Decodage_CISC _table_100 = {&mask_100, table_table_100};
Table_Decodage_CISC *avr_table_100 = &_table_100;

static Decode_Ent table_table_011[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_SUBI_RD__D}	/* SUBI_RD__D, 16 bits, mask=1111000000000000, val=0101XXXXXXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_ANDI_RD__RD}	/* ANDI_RD__RD, 16 bits, mask=1111000000000000, val=0111XXXXXXXXXXXX */
};
static uint32_t tab_mask_011[1] = {0X20000000};
static mask_t mask_011 = {
	tab_mask_011,	16};
static Table_Decodage_CISC _table_011 = {&mask_011, table_table_011};
Table_Decodage_CISC *avr_table_011 = &_table_011;

static Decode_Ent table_table_010[2] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_SBCI_RD__D}	/* SBCI_RD__D, 16 bits, mask=1111000000000000, val=0100XXXXXXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_ORI_RD__D}	/* ORI_RD__D, 16 bits, mask=1111000000000000, val=0110XXXXXXXXXXXX */
};
static uint32_t tab_mask_010[1] = {0X20000000};
static mask_t mask_010 = {
	tab_mask_010,	16};
static Table_Decodage_CISC _table_010 = {&mask_010, table_table_010};
Table_Decodage_CISC *avr_table_010 = &_table_010;

static Decode_Ent table_table_001_0[4] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_CSPE_RD__RD}	/* CSPE_RD__RD, 16 bits, mask=1111110000000000, val=000100XXXXXXXXXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_CP_RD__RD}	/* CP_RD__RD, 16 bits, mask=1111110000000000, val=000101XXXXXXXXXX */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_SUB_RD__RD}	/* SUB_RD__RD, 16 bits, mask=1111110000000000, val=000110XXXXXXXXXX */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_ADC_RD__RD}	/* ADC_RD__RD, 16 bits, mask=1111110000000000, val=000111XXXXXXXXXX */
};
static uint32_t tab_mask_001_0[1] = {0XC000000};
static mask_t mask_001_0 = {
	tab_mask_001_0,	16};
static Table_Decodage_CISC _table_001_0 = {&mask_001_0, table_table_001_0};
Table_Decodage_CISC *avr_table_001_0 = &_table_001_0;

static Decode_Ent table_table_001[2] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_001_0},
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_CPI_RD__0X02X__3B_D}	/* CPI_RD__0X02X__3B_D, 16 bits, mask=1111000000000000, val=0011XXXXXXXXXXXX */
};
static uint32_t tab_mask_001[1] = {0X20000000};
static mask_t mask_001 = {
	tab_mask_001,	16};
static Table_Decodage_CISC _table_001 = {&mask_001, table_table_001};
Table_Decodage_CISC *avr_table_001 = &_table_001;

static Decode_Ent table_table_000_000_11[4] = {
	/* 0X0,0 */	{INSTRUCTION, (void *)AVR_MULSU_RD__RD}	/* MULSU_RD__RD, 16 bits, mask=1111111110001000, val=000000110XXX0XXX */,
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_FMUL_RD__RD}	/* FMUL_RD__RD, 16 bits, mask=1111111110001000, val=000000110XXX1XXX */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_FMULS_RD__RD}	/* FMULS_RD__RD, 16 bits, mask=1111111110001000, val=000000111XXX0XXX */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_FMULSU_RD__RD}	/* FMULSU_RD__RD, 16 bits, mask=1111111110001000, val=000000111XXX1XXX */
};
static uint32_t tab_mask_000_000_11[1] = {0X880000};
static mask_t mask_000_000_11 = {
	tab_mask_000_000_11,	16};
static Table_Decodage_CISC _table_000_000_11 = {&mask_000_000_11, table_table_000_000_11};
Table_Decodage_CISC *avr_table_000_000_11 = &_table_000_000_11;

static Decode_Ent table_table_000_000[4] = {
	{INSTRUCTION, (void *)AVR_UNKNOWN},
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_MOVW_RD_3AD__RD_3AD}	/* MOVW_RD_3AD__RD_3AD, 16 bits, mask=1111111100000000, val=00000001XXXXXXXX */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_MULS_RD__RD}	/* MULS_RD__RD, 16 bits, mask=1111111100000000, val=00000010XXXXXXXX */,
	/* 0X3,3 */	{TABLEFETCH, &_table_000_000_11}
};
static uint32_t tab_mask_000_000[1] = {0X3000000};
static mask_t mask_000_000 = {
	tab_mask_000_000,	16};
static Table_Decodage_CISC _table_000_000 = {&mask_000_000, table_table_000_000};
Table_Decodage_CISC *avr_table_000_000 = &_table_000_000;

static Decode_Ent table_table_000[8] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_000_000},
	/* 0X1,1 */	{INSTRUCTION, (void *)AVR_CPC_RD__RD}	/* CPC_RD__RD, 16 bits, mask=1111110000000000, val=000001XXXXXXXXXX */,
	/* 0X2,2 */	{INSTRUCTION, (void *)AVR_SBC_RD__RD}	/* SBC_RD__RD, 16 bits, mask=1111110000000000, val=000010XXXXXXXXXX */,
	/* 0X3,3 */	{INSTRUCTION, (void *)AVR_ADD_RD__RD}	/* ADD_RD__RD, 16 bits, mask=1111110000000000, val=000011XXXXXXXXXX */,
	/* 0X4,4 */	{INSTRUCTION, (void *)AVR_AND_RD__RD}	/* AND_RD__RD, 16 bits, mask=1111110000000000, val=001000XXXXXXXXXX */,
	/* 0X5,5 */	{INSTRUCTION, (void *)AVR_EOR_RD__RD}	/* EOR_RD__RD, 16 bits, mask=1111110000000000, val=001001XXXXXXXXXX */,
	/* 0X6,6 */	{INSTRUCTION, (void *)AVR_OR_RD__RD}	/* OR_RD__RD, 16 bits, mask=1111110000000000, val=001010XXXXXXXXXX */,
	/* 0X7,7 */	{INSTRUCTION, (void *)AVR_MOV_RD__RD}	/* MOV_RD__RD, 16 bits, mask=1111110000000000, val=001011XXXXXXXXXX */
};
static uint32_t tab_mask_000[1] = {0X2C000000};
static mask_t mask_000 = {
	tab_mask_000,	16};
static Table_Decodage_CISC _table_000 = {&mask_000, table_table_000};
Table_Decodage_CISC *avr_table_000 = &_table_000;

static Decode_Ent table_table[8] = {
	/* 0X0,0 */	{TABLEFETCH, &_table_000},
	/* 0X1,1 */	{TABLEFETCH, &_table_001},
	/* 0X2,2 */	{TABLEFETCH, &_table_010},
	/* 0X3,3 */	{TABLEFETCH, &_table_011},
	/* 0X4,4 */	{TABLEFETCH, &_table_100},
	/* 0X5,5 */	{TABLEFETCH, &_table_101},
	/* 0X6,6 */	{TABLEFETCH, &_table_110},
	/* 0X7,7 */	{TABLEFETCH, &_table_111}
};
static uint32_t tab_mask[1] = {0XD0000000};
static mask_t mask = {
	tab_mask,	32};
static Table_Decodage_CISC _table = {&mask, table_table};
Table_Decodage_CISC *avr_table = &_table;




#if defined(__cplusplus)
}
#endif

#endif /* GLISS_AVR_INCLUDE_AVR_FETCH_TABLE_H */
