/* Generated by GLISS V2.0 Copyright (c) 2009 IRIT - UPS (125/05/23 10:52:00) */
#ifndef MOS6502_PLATFORM_H
#define MOS6502_PLATFORM_H

#include <mos6502/api.h>
#include <mos6502/mem.h>
#include <mos6502/grt.h>
#include <mos6502/error.h>
#include <mos6502/gen_int.h>
#include <mos6502/env.h>
#include <mos6502/loader.h>
#include <mos6502/code.h>


/* mos6502_platform_t structure */
struct mos6502_platform_t
{
	int usage;

	/* entry point of the simulated program */
	mos6502_address_t entry;
	/* initial sp, argv, envp ... */
	mos6502_env_t *sys_env;

	union
	{
		mos6502_memory_t *array[0];
		struct
		{
			mos6502_memory_t *ram;
			mos6502_memory_t *ppuram;
			mos6502_memory_t *apuram;
			mos6502_memory_t *cartridge;

		} named;
	} mems;
	MOS6502_MEM_STATE
	MOS6502_GRT_STATE
	MOS6502_ERROR_STATE
	MOS6502_GEN_INT_STATE
	MOS6502_ENV_STATE
	MOS6502_LOADER_STATE
	MOS6502_CODE_STATE

};

/* functions */

#endif	/* MOS6502_PLATFORM_H */
