/* Generated by GLISS V2.0 Copyright (c) 2009 IRIT - UPS (125/04/14 21:47:43) */
#ifndef AVR_PLATFORM_H
#define AVR_PLATFORM_H

#include <avr/api.h>
#include <avr/mem.h>
#include <avr/grt.h>
#include <avr/error.h>
#include <avr/gen_int.h>
#include <avr/env.h>
#include <avr/loader.h>
#include <avr/code.h>


/* avr_platform_t structure */
struct avr_platform_t
{
	int usage;

	/* entry point of the simulated program */
	avr_address_t entry;
	/* initial sp, argv, envp ... */
	avr_env_t *sys_env;

	union
	{
		avr_memory_t *array[0];
		struct
		{
			avr_memory_t *FLASH;
			avr_memory_t *M;

		} named;
	} mems;
	AVR_MEM_STATE
	AVR_GRT_STATE
	AVR_ERROR_STATE
	AVR_GEN_INT_STATE
	AVR_ENV_STATE
	AVR_LOADER_STATE
	AVR_CODE_STATE

};

/* functions */

#endif	/* AVR_PLATFORM_H */
