/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef AVR_AVR_INCLUDE_AVR_CODE_H
#define AVR_AVR_INCLUDE_AVR_CODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define AVR_CODE_STATE
#define AVR_CODE_INIT(s)
#define AVR_CODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* AVR_AVR_INCLUDE_AVR_CODE_H */
