/* AVR template generated by GLISS2 (125/04/14 21:47:45) */

#define TARGET_ENDIANNESS little
#define HOST_ENDIANNESS little

#define AVR_ORDER_BYTES_CISC \
	word = (buff[1] << 24) | (buff[0] << 16) | (buff[3] << 8) | buff[2];
