/* Generated by gep (125/04/14 21:47:45) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_AVR_INCLUDE_AVR_DECODE_H
#define GLISS_AVR_INCLUDE_AVR_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#define AVR_DECODE_STATE
#define AVR_DECODE_INIT(s)
#define AVR_DECODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_AVR_INCLUDE_AVR_DECODE_H */
