/* Generated by gep (125/04/14 21:47:43) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_AVR_INCLUDE_AVR_FETCH_H
#define GLISS_AVR_INCLUDE_AVR_FETCH_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include "api.h"
#include "config.h"

#define AVR_FETCH_STATE
#define AVR_FETCH_INIT(s)
#define AVR_FETCH_DESTROY(s)

/* fetch structure */
struct avr_fetch_t
{
	/* the memory which we are supposed to fetch from, useful on Harvard architectures where we deal with several memories */
	avr_memory_t *mem;
};

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_AVR_INCLUDE_AVR_FETCH_H */
