/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef AVR_AVR_INCLUDE_GEN_INT_H
#define AVR_AVR_INCLUDE_GEN_INT_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define AVR_GEN_INT_STATE
#define AVR_GEN_INT_INIT(s)
#define AVR_GEN_INT_DESTROY(s)

/* struct used to store masks and as buffer for instruction codes or any binary value which cannot fit into an uintN_t */
/* chunks are arranged in the same order as in memory, msb first, lsb last */
struct mask_t {
	uint32_t *mask;
	int bit_length;
};

uint64_t extract_mask(struct mask_t *inst, struct mask_t *mask);
uint32_t get_mask_chunk(struct mask_t *mask, int idx);
int get_mask_length(struct mask_t *mask);
void set_mask_chunk(struct mask_t *mask, int idx, uint32_t val);
void set_mask_length(struct mask_t *mask, int val);

#if defined(__cplusplus)
}
#endif

#endif /* AVR_AVR_INCLUDE_GEN_INT_H */
